// Writes the R and Python clients' functions for every CytoWeave action from clients/tools.json
// (the agent tools' names, descriptions and argument schemas, which go test keeps equal to the
// program's): clients/python/src/cytoweave/_tools.py, clients/r/R/tools.R with a help page per
// function in clients/r/man/, the R NAMESPACE, and both packages' versions (main.go's). With
// --check it writes nothing and fails when a file differs (CI).
//
//   go test -run TestTheClientsToolListIsCurrent -update   # after changing a tool in mcp.go
//   node clients/generate.mjs

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const check = process.argv.includes('--check');
const tools = JSON.parse(readFileSync(join(here, 'tools.json'), 'utf8'));
const version = /^var version = "([^"]+)"$/m.exec(readFileSync(join(root, 'main.go'), 'utf8'))[1];
const HEADER = 'Generated by clients/generate.mjs from clients/tools.json; do not edit by hand.';
// The clients' own functions, which no tool may shadow (cw.call, cw_tools, …).
const OWN = new Set(['call', 'tools', 'version', 'url', 'token', 'client', 'timeout', 'connect', 'default', 'save_image']);
const clash = tools.filter((t) => OWN.has(t.name)).map((t) => t.name);
if (clash.length) throw new Error(`Tools named like the clients' own functions: ${clash.join(', ')}. Rename them in mcp.go.`);

// groupBy → group_by, rerunQC → rerun_qc, nNeighbors → n_neighbors.
const snake = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/([A-Z])([A-Z][a-z])/g, '$1_$2').toLowerCase();
const PYTHON_KEYWORDS = new Set(['and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield', 'self', 'file']);
const R_RESERVED = new Set(['if', 'else', 'repeat', 'while', 'function', 'for', 'next', 'break', 'TRUE', 'FALSE', 'NULL', 'Inf', 'NaN', 'NA', 'in', 'cw', 'file']);

// The arguments of a tool: the required ones first, in the order the tool lists them (positional
// in R and Python), then the others by name.
function argumentsOf(tool) {
  const properties = tool.inputSchema.properties ?? {};
  const required = tool.inputSchema.required ?? [];
  return [
    ...required.map((name) => ({ name, spec: properties[name], required: true })),
    ...Object.entries(properties).filter(([name]) => !required.includes(name)).map(([name, spec]) => ({ name, spec, required: false })),
  ];
}

function describeType(spec) {
  if (spec.enum) return `one of ${spec.enum.map((v) => `"${v}"`).join(', ')}`;
  if (spec.type === 'array') return 'a list of strings';
  if (spec.type === 'object') return 'a named list (Python: a dict)';
  if (spec.type === 'boolean') return 'TRUE or FALSE (Python: True or False)';
  if (spec.type === 'number') return 'a number';
  if (spec.type === 'string') return 'a string';
  return 'any value';
}

// A description as a sentence followed by a space, or nothing when there is none.
const sentence = (text) => (!text ? '' : /[.!?]$/.test(text) ? `${text} ` : `${text}. `);
const imageTool = (tool) => tool.name === 'render_plot';

// --- Python -------------------------------------------------------------------------------------

function pythonName(name) {
  const s = snake(name);
  return PYTHON_KEYWORDS.has(s) ? `${s}_` : s;
}

function wrapText(text, width, indent) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines = [];
  let line = '';
  for (const word of words) {
    if (line && line.length + 1 + word.length > width) {
      lines.push(line);
      line = word;
    } else line = line ? `${line} ${word}` : word;
  }
  if (line) lines.push(line);
  return lines.map((l) => `${indent}${l}`).join('\n');
}

function pythonTools() {
  const out = [`# ${HEADER}`, '', '"""Every CytoWeave action as a method; CytoWeave (client.py) adds the connection."""', '', '', 'class Tools:', '    """The actions of CytoWeave\'s remote control, one method each."""', ''];
  for (const tool of tools) {
    const args = argumentsOf(tool);
    const params = ['self'];
    let keywordOnly = false;
    for (const a of args) {
      if (!a.required && !keywordOnly) {
        params.push('*');
        keywordOnly = true;
      }
      params.push(a.required ? pythonName(a.name) : `${pythonName(a.name)}=None`);
    }
    if (imageTool(tool)) {
      if (!keywordOnly) params.push('*');
      params.push('file=None');
    }
    out.push(`    def ${tool.name}(${params.join(', ')}):`);
    out.push(`        """${tool.title}.`, '', wrapText(tool.description.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"'), 92, '        '));
    if (args.length || imageTool(tool)) {
      out.push('', '        Args:');
      for (const a of args) out.push(wrapText(`${pythonName(a.name)}: ${sentence(a.spec.description ?? '')}${a.required ? 'Required' : 'Optional'}; ${describeType(a.spec)}.`, 88, '            ').replace(/^ {12}/, '            ').replace(/\n {12}/g, '\n                '));
      if (imageTool(tool)) out.push('            file: Optional; save the plot to this path as a PNG file.');
    }
    out.push('', '        Returns:', '            A Result: the message and the data CytoWeave answered with.', '        """');
    const mapping = args.map((a) => `"${a.name}": ${pythonName(a.name)}`).join(', ');
    if (imageTool(tool)) {
      out.push(`        result = self.call("${tool.name}", **{${mapping}})`, '        if file is not None:', '            result.save_image(file)', '        return result', '');
    } else {
      out.push(`        return self.call("${tool.name}"${mapping ? `, **{${mapping}}` : ''})`, '');
    }
  }
  return `${out.join('\n').trimEnd()}\n`;
}

// --- R ------------------------------------------------------------------------------------------

function rName(name) {
  const s = snake(name);
  return R_RESERVED.has(s) ? `${s}_` : s;
}

// Rd text: backslash, braces and percent escaped.
const rd = (text) => String(text).replace(/\\/g, '\\\\').replace(/([{}%])/g, '\\$1');
const roxygen = (text) => String(text).replace(/%/g, '\\%');

function rUsage(tool) {
  const args = argumentsOf(tool);
  const parts = args.map((a) => (a.required ? rName(a.name) : `${rName(a.name)} = NULL`));
  if (imageTool(tool)) parts.push('file = NULL');
  parts.push('cw = cw_default()');
  return `cw_${tool.name}(${parts.join(', ')})`;
}

function rTools() {
  const out = [`# ${HEADER}`, ''];
  for (const tool of tools) {
    const args = argumentsOf(tool);
    out.push(`#' ${roxygen(tool.title)}`, "#'", ...wrapText(roxygen(tool.description), 92, "#' ").split('\n'), "#'");
    for (const a of args) out.push(...wrapText(roxygen(`@param ${rName(a.name)} ${sentence(a.spec.description ?? '')}${a.required ? 'Required' : 'Optional'}; ${describeType(a.spec)}.`), 92, "#' ").split('\n'));
    if (imageTool(tool)) out.push("#' @param file Optional; save the plot to this path as a PNG file.");
    out.push("#' @param cw A connection from cw_connect() (default: the last one made).", "#' @return A cytoweave_result: the message and the data CytoWeave answered with.", "#' @export");
    const signature = rUsage(tool).replace(/^cw_[a-z_]+\(/, '').replace(/\)$/, '');
    out.push(`cw_${tool.name} <- function(${signature}) {`);
    const values = args.map((a) => {
      const value = a.spec.type === 'array' ? `.cw_array(${rName(a.name)})` : rName(a.name);
      return `${/^[A-Za-z][A-Za-z0-9_.]*$/.test(a.name) ? a.name : `\`${a.name}\``} = ${value}`;
    });
    const call = `cw_call("${tool.name}", ${values.length ? `${values.join(', ')}, ` : ''}cw = cw)`;
    if (imageTool(tool)) out.push(`  result <- ${call}`, '  if (!is.null(file)) cw_save_image(result, file)', '  result', '}', '');
    else out.push(`  ${call}`, '}', '');
  }
  return `${out.join('\n').trimEnd()}\n`;
}

function rHelpPage(tool) {
  const args = argumentsOf(tool);
  const items = args.map((a) => `\\item{${rName(a.name)}}{${rd(`${sentence(a.spec.description ?? '')}${a.required ? 'Required' : 'Optional'}; ${describeType(a.spec)}.`)}}`);
  if (imageTool(tool)) items.push('\\item{file}{Optional; save the plot to this path as a PNG file.}');
  items.push('\\item{cw}{A connection from \\code{\\link{cw_connect}} (default: the last one made).}');
  return [
    `% ${HEADER}`,
    `\\name{cw_${tool.name}}`,
    `\\alias{cw_${tool.name}}`,
    `\\title{${rd(tool.title)}}`,
    '\\usage{',
    rUsage(tool),
    '}',
    '\\arguments{',
    ...items,
    '}',
    '\\value{',
    'A \\code{cytoweave_result}: the \\code{message} and the \\code{data} CytoWeave answered with.',
    '}',
    '\\description{',
    rd(tool.description),
    '}',
    `\\seealso{\\code{\\link{cw_call}}, which sends any action by its name (here \\code{"${tool.name}"}).}`,
    '',
  ].join('\n');
}

function rNamespace() {
  const core = ['cw_call', 'cw_connect', 'cw_default', 'cw_save_image', 'cw_tools'];
  return [
    `# ${HEADER}`,
    ...[...core, ...tools.map((t) => `cw_${t.name}`)].sort().map((name) => `export(${name})`),
    'S3method(as.data.frame,cytoweave_result)',
    'S3method(print,cytoweave)',
    'S3method(print,cytoweave_result)',
    '',
  ].join('\n');
}

// --- Writing ------------------------------------------------------------------------------------

const files = new Map();
files.set('python/src/cytoweave/_tools.py', pythonTools());
files.set('r/R/tools.R', rTools());
files.set('r/NAMESPACE', rNamespace());
for (const tool of tools) files.set(`r/man/cw_${tool.name}.Rd`, rHelpPage(tool));
// Versions: the program's.
const pyproject = readFileSync(join(here, 'python/pyproject.toml'), 'utf8');
files.set('python/pyproject.toml', pyproject.replace(/^version = "[^"]*"$/m, `version = "${version}"`));
const description = readFileSync(join(here, 'r/DESCRIPTION'), 'utf8');
files.set('r/DESCRIPTION', description.replace(/^Version: .*$/m, `Version: ${version}`));
const init = readFileSync(join(here, 'python/src/cytoweave/__init__.py'), 'utf8');
files.set('python/src/cytoweave/__init__.py', init.replace(/^__version__ = "[^"]*"$/m, `__version__ = "${version}"`));

// Help pages of tools that no longer exist.
const generatedPages = existsSync(join(here, 'r/man')) ? readdirSync(join(here, 'r/man')).filter((f) => f.endsWith('.Rd') && readFileSync(join(here, 'r/man', f), 'utf8').includes(HEADER)) : [];
const stale = generatedPages.filter((f) => !files.has(`r/man/${f}`));

const differ = [];
for (const [path, text] of files) {
  const full = join(here, path);
  const current = existsSync(full) ? readFileSync(full, 'utf8') : null;
  if (current === text) continue;
  differ.push(path);
  if (!check) {
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, text);
  }
}
for (const f of stale) {
  differ.push(`r/man/${f} (no such tool)`);
  if (!check) rmSync(join(here, 'r/man', f));
}
if (check) {
  if (differ.length) {
    console.error(`The clients are out of date with clients/tools.json or main.go: ${differ.join(', ')}. Run node clients/generate.mjs.`);
    process.exit(1);
  }
  console.log(`The clients' ${tools.length} tool functions and version ${version} are current.`);
} else {
  console.log(differ.length ? `Wrote ${differ.length} file(s): ${differ.slice(0, 6).join(', ')}${differ.length > 6 ? ', …' : ''}` : 'Nothing to change.');
}
