// Writes web/lib/cell-ontology.js from the curated Cell Ontology terms in cell-ontology-terms.json
// (labels, synonyms and definitions verbatim from the Cell Ontology release named there, with the
// marker phenotype each implies).
//
//   node validation/reference/generate_cell_ontology.mjs [--obo path/to/cl.obo]
//
// With --obo, each term's ancestors among the curated terms (its is_a closure in the Cell
// Ontology) are first computed from that release's cl.obo (http://purl.obolibrary.org/obo/cl.obo,
// 17 MB, not kept in the repository) and stored in the JSON; ontology.js uses them to prefer a
// specific term over its ancestors.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const jsonPath = path.join(here, 'cell-ontology-terms.json');
const t = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

const oboAt = process.argv.indexOf('--obo');
if (oboAt > 0) {
  const isA = new Map();
  let id = null;
  for (const line of fs.readFileSync(process.argv[oboAt + 1], 'utf8').split('\n')) {
    if (line.startsWith('[')) id = null;
    if (line.startsWith('id: CL:')) id = line.slice(4).trim();
    const m = id && /^is_a: (CL:\d{7})/.exec(line);
    if (m) isA.set(id, [...(isA.get(id) ?? []), m[1]]);
  }
  const curated = new Set(t.terms.map((x) => x.id));
  for (const term of t.terms) {
    const seen = new Set();
    const stack = [...(isA.get(term.id) ?? [])];
    while (stack.length) {
      const p = stack.pop();
      if (seen.has(p)) continue;
      seen.add(p);
      stack.push(...(isA.get(p) ?? []));
    }
    term.ancestors = [...seen].filter((a) => curated.has(a)).sort();
  }
  t.meta.ancestors = `ancestors: each term's ancestors among the curated terms, its is_a closure in cl.obo of release ${t.meta.clVersion}`;
  fs.writeFileSync(jsonPath, `${JSON.stringify(t, null, 2)}\n`);
}

// Marker states accepted for a written state (see ontology.js).
const norm = (v) => {
  const s = String(v).trim().toLowerCase();
  if (s === '+') return ['+', 'high'];
  if (s === '+ (high)') return ['high', '+'];
  if (s === 'high' || s === 'bright') return ['high'];
  if (s === '-' || s.startsWith('- (or')) return ['-', 'low'];
  if (s === 'dim') return ['low'];
  if (s === 'low' || s === 'very low' || s === '- or low' || s === 'low/-') return ['low', '-'];
  if (s === '+/low') return ['+', 'low', 'high', 'mid'];
  if (s === 'int' || s === 'low/intermediate') return ['low', 'mid'];
  return null;
};
const terms = t.terms.map((x) => {
  const practice = x.practice?.phenotype;
  const raw = practice ?? x.markers ?? {};
  const requires = {};
  const anyOf = [];
  for (const [marker, v] of Object.entries(raw)) {
    const m = /^\+ and\/or (\S+) \+$/.exec(String(v).trim());
    if (m) { anyOf.push([[marker, ['+', 'high']], [m[1], ['+', 'high']]]); continue; }
    const states = norm(v);
    if (states) requires[marker] = states;
  }
  // CytoWeave's addition: NK1.1, the conventional mouse NK cell marker, among the NK markers (NK
  // cells), and in place of CD56 for NK T cells.
  if (x.id === 'CL:0000623') for (const group of anyOf) if (group.some(([m]) => m === 'CD56')) group.push(['NK1.1', ['+', 'high']]);
  if (x.id === 'CL:0000814' && requires.CD56) {
    anyOf.push([['CD56', requires.CD56], ['NK1.1', ['+', 'high']]]);
    delete requires.CD56;
  }
  return { id: x.id, label: x.label, ...(x.synonyms?.length ? { synonyms: x.synonyms } : {}), definition: x.definition, parents: x.parents ?? [], ancestors: x.ancestors ?? [], requires, ...(anyOf.length ? { anyOf } : {}), source: practice ? 'practice' : 'cl', ...(practice ? { citations: x.practice.citations } : {}) };
});
const meta = { release: t.meta.clVersion, license: 'CC BY 4.0', source: 'http://purl.obolibrary.org/obo/cl.obo', citation: 'Tan SZK et al. The Cell Ontology in the age of single-cell omics. Sci Data 13, 946 (2026). doi:10.1038/s41597-026-07173-8' };
const out = `// Cell Ontology terms for the populations flow cytometry gates in blood, PBMC and lymphoid tissue,
// with the marker phenotype each implies, for ontology.js to suggest terms from a population's
// phenotype. Generated by validation/reference/generate_cell_ontology.mjs from a curated list of ${terms.length} terms of the Cell Ontology release ${t.meta.clVersion}
// (cl.obo; labels, synonyms and definitions verbatim, checked against EBI OLS4).
//
// ancestors: the term's ancestors among these terms (its is_a closure in CL).
// requires: marker → accepted states ("+" also accepts high; "-" also accepts low; "high" and
// "bright" need high, "dim" low). For terms with a
// conventional flow phenotype (source "practice": Maecker et al. 2012, or the OMIPs listed in
// citations), that phenotype; otherwise the term's own marker axioms in CL. anyOf: groups of which
// at least one marker must hold (e.g. CD56 or CD16 for NK cells; CytoWeave adds NK1.1, the mouse
// NK marker, to that group).
//
// Contains text from the Cell Ontology, CC BY 4.0 (http://creativecommons.org/licenses/by/4.0/).
// Cite: Tan SZK et al. The Cell Ontology in the age of single-cell omics. Sci Data 13, 946 (2026),
// doi:10.1038/s41597-026-07173-8.

export const CELL_ONTOLOGY = ${JSON.stringify(meta, null, 2)};

export const PRACTICE_CITATIONS = {
  Maecker2012: 'Maecker HT, McCoy JP, Nussenblatt R. Standardizing immunophenotyping for the Human Immunology Project. Nat Rev Immunol. 2012;12(3):191–200. doi:10.1038/nri3158',
  'OMIP-101': 'Imbratta C, Reid TD, Toefy A, et al. OMIP-101: 27-color flow cytometry panel for immunophenotyping of major leukocyte populations in fixed whole blood. Cytometry A. 2024;105(3):165–170. doi:10.1002/cyto.a.24827',
  'OMIP-069': 'Park LM, Lannigan J, Jaimes MC. OMIP-069: Forty-color full spectrum flow cytometry panel for deep immunophenotyping of major cell subsets in human peripheral blood. Cytometry A. 2020;97(10):1044–1051. doi:10.1002/cyto.a.24213',
  'OMIP-090': 'Stroukov W, Mastronicola D, Albany CJ, et al. OMIP-090: A 20-parameter flow cytometry panel for rapid analysis of cell diversity and homing capacity in human conventional and regulatory T cells. Cytometry A. 2023;103(5):362–367. doi:10.1002/cyto.a.24720',
};

export const TERMS = [
${terms.map((x) => `  ${JSON.stringify(x)}`).join(',\n')},
];
`;
fs.writeFileSync(path.join(here, '../../web/lib/cell-ontology.js'), out);
const skipped = t.terms.flatMap((x) => Object.entries(x.practice?.phenotype ?? x.markers ?? {}).filter(([, v]) => !norm(v) && !/and\/or/.test(v)).map(([m, v]) => `${x.id} ${m}=${v}`));
console.log(terms.length, 'terms; unparsed:', skipped);
