# Generated by clients/generate.mjs from clients/tools.json; do not edit by hand.

"""Every CytoWeave action as a method; CytoWeave (client.py) adds the connection."""


class Tools:
    """The actions of CytoWeave's remote control, one method each."""

    def workspace_summary(self):
        """Describe the workspace.

        The open workspace: its samples (name, events, role, metadata, channels with markers),
        groups, the gating tree with counts for the current sample, compensation matrices, derived
        results, and what the window shows. Start here.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("workspace_summary")

    def open_files(self, paths):
        """Open FCS files.

        Open FCS files, folders of FCS files (each folder becomes a group), CytoWeave workspaces
        (.cwz), FlowJo workspaces (.wsp) and FlowJo 11 workbenches (.flowjo), FACSDiva experiments
        exported as XML (these open in the import dialog for the user, with a fidelity report and a
        count comparison), SpectroFlo experiments (.Expt, whose reference controls the user can mark
        for spectral unmixing), Gating-ML files, or CSV files of events (a row per event, a column
        per channel; each becomes a sample, with the columns' kinds and scales guessed and checked,
        reported in data.csv), by absolute path on this computer. A CSV whose first column names
        samples annotates them instead.

        Args:
            paths: Absolute paths of files or folders. Required; a list of strings.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("open_files", **{"paths": paths})

    def open_example(self, id):
        """Open an example experiment.

        Generate and open a simulated example experiment as a new workspace: pbmc-immunophenotyping,
        flowjo-workspace (four samples and a FlowJo workspace, which opens in the FlowJo import
        dialog for the user), spectral-25color, cell-cycle, proliferation, cytof-cohort,
        cytof-barcoded (a pooled, palladium-barcoded plate), index-sort, qc-showcase or bead-qc (30
        daily runs of multi-level beads for Q, B and Levey–Jennings).

        Args:
            id: Required; one of "pbmc-immunophenotyping", "flowjo-workspace", "spectral-25color",
                "cell-cycle", "proliferation", "cytof-cohort", "cytof-barcoded", "index-sort",
                "qc-showcase", "bead-qc".

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("open_example", **{"id": id})

    def select(self, *, population=None, sample=None, view=None):
        """Show a sample, population or view.

        Change what the window shows: a sample, a population, and/or a view (gate, qc, compensate,
        spectral, explore, tables, compare, figures, report).

        Args:
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Optional; a string.
            sample: Sample name or id (default: the sample shown in the window). Optional; a string.
            view: View to show. Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("select", **{"population": population, "sample": sample, "view": view})

    def list_populations(self, *, sample=None):
        """List populations with counts.

        The gating tree for a sample: every population's path, gate type and channels, event count,
        % of parent and % of total.

        Args:
            sample: Sample name or id (default: the sample shown in the window). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("list_populations", **{"sample": sample})

    def population_statistics(self, *, channels=None, population=None, sample=None):
        """Statistics of a population.

        Count, frequencies and per-channel statistics (median, mean, geometric mean, SD, robust SD,
        CV, robust CV, percentiles) of one population in one sample, on compensated values.

        Args:
            channels: Channels or markers (default: all fluorescence channels). Optional; a list of
                strings.
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Optional; a string.
            sample: Sample name or id (default: the sample shown in the window). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("population_statistics", **{"channels": channels, "population": population, "sample": sample})

    def statistics_table(self, *, bead_population=None, beads_per_tube=None, channel=None, control=None, control_population=None, dilution=None, group=None, populations=None, sample_volume=None, statistic=None):
        """A statistic across samples.

        One or more statistics of one or more populations for every sample (or a group): e.g.
        freqParent of CD4 T cells, or median of CD25 in Tregs. Statistics: count, freqParent,
        freqTotal, freqGrandparent, median, mean, geomean, sd, rsd, cv, rcv, percentile, mode,
        positive; for rare events countLow and countHigh (exact Poisson 95% limits), countCV,
        freqLow and freqHigh (exact binomial 95% limits of freqParent); concentration (/µL from
        $VOL) and absoluteCount (/µL from counting beads); and, against a control sample's
        population on the channel, overton and sed (% positive), pbPositive and pbT (probability
        binning) and ksD.

        Args:
            bead_population: For absoluteCount: the counting beads' population. Optional; a string.
            beads_per_tube: For absoluteCount: beads in the tube. Optional; a number.
            channel: Channel or marker for channel statistics. Optional; a string.
            control: Control sample for overton, sed, pbPositive, pbT and ksD (e.g. an FMO).
                Optional; a string.
            control_population: The control's population (default: the same population). Optional; a
                string.
            dilution: For concentration and absoluteCount: a dilution factor, or the sample
                annotation that holds it. Optional; a string.
            group: Group name (default: all samples). Optional; a string.
            populations: Populations (default: all). Optional; a list of strings.
            sample_volume: For absoluteCount: µL of sample in the tube. Optional; a number.
            statistic: Statistic id (default freqParent). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("statistics_table", **{"beadPopulation": bead_population, "beadsPerTube": beads_per_tube, "channel": channel, "control": control, "controlPopulation": control_population, "dilution": dilution, "group": group, "populations": populations, "sampleVolume": sample_volume, "statistic": statistic})

    def render_plot(self, x, *, height=None, population=None, sample=None, type=None, width=None, y=None, file=None):
        """Render a plot.

        A PNG image of a plot: a population of a sample on one or two channels, with the child gates
        drawn and labeled. Types: pseudocolor, dot, density, contour, zebra, histogram.

        Args:
            x: X channel or marker. Required; a string.
            height: Height in pixels (default 480). Optional; a number.
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Optional; a string.
            sample: Sample name or id (default: the sample shown in the window). Optional; a string.
            type: Plot type. Optional; a string.
            width: Width in pixels (default 520). Optional; a number.
            y: Y channel or marker (omit for a histogram). Optional; a string.
            file: Optional; save the plot to this path as a PNG file.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        result = self.call("render_plot", **{"x": x, "height": height, "population": population, "sample": sample, "type": type, "width": width, "y": y})
        if file is not None:
            result.save_image(file)
        return result

    def create_gate(self, type, x, coordinates, *, name=None, parent=None, sample=None, y=None):
        """Create a gate.

        Add a gate under a parent population. Coordinates are data values (as on the plot axes).
        Types and coordinates: rectangle {xMin, xMax, yMin, yMax} (omit a bound to leave it open),
        polygon {vertices: [[x, y], ...]}, ellipse {center: [x, y], semiAxes in fractions of the
        axes [rx, ry], angle in degrees}, range on one channel {min, max}, quadrant {at: [x, y]}
        (creates four populations), split on one channel {threshold} (two populations). The gate is
        proposed for the user's review (shown as proposed, usable as a parent at once). Returns the
        new populations with their counts.

        Args:
            type: Required; one of "rectangle", "polygon", "ellipse", "range", "quadrant", "split".
            x: X channel or marker. Required; a string.
            coordinates: Type-specific coordinates in data values. Required; a named list (Python: a
                dict).
            name: Name (default: from the markers). Optional; a string.
            parent: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events" or
                omitted for all events. Optional; a string.
            sample: Sample whose counts are reported (default: the current sample); the gate applies
                to every sample. Optional; a string.
            y: Y channel or marker (not for range or split). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("create_gate", **{"type": type, "x": x, "coordinates": coordinates, "name": name, "parent": parent, "sample": sample, "y": y})

    def auto_gate(self, method, x, *, at=None, name=None, parent=None, sample=None, y=None):
        """Propose a gate from the data.

        Add a gate found from the data's density: method "density" gates the population around a
        point (at: [x, y] in data values) like a magic wand; "singlets" gates single cells on an
        area-versus-height plot (x = FSC-A, y = FSC-H); "valley" splits one channel at the density
        minimum between its two main modes. The explanation says what was found. The gate is
        proposed for the user's review.

        Args:
            method: Required; one of "density", "singlets", "valley".
            x: X channel or marker. Required; a string.
            at: [x, y] data values (density). Optional; a list of strings.
            name: Name. Optional; a string.
            parent: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events" or
                omitted for all events. Optional; a string.
            sample: Sample name or id (default: the sample shown in the window). Optional; a string.
            y: Y channel or marker. Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("auto_gate", **{"method": method, "x": x, "at": at, "name": name, "parent": parent, "sample": sample, "y": y})

    def edit_gate(self, population, *, color=None, delete=None, name=None):
        """Rename, recolor or delete a gate.

        Rename a population, change its color, or delete it (with its subpopulations). Changes to
        gates the user has accepted wait for the user's review; changes to gates you proposed apply
        at once.

        Args:
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Required; a string.
            color: New color (#rrggbb). Optional; a string.
            delete: Optional; TRUE or FALSE (Python: True or False).
            name: New name. Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("edit_gate", **{"population": population, "color": color, "delete": delete, "name": name})

    def review_gate(self, population):
        """Review a gate across samples.

        A gate's frequency on every sample with a robust z-score against the cohort and the boundary
        robustness (how much the frequency depends on exactly where the boundary is), outliers
        first.

        Args:
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Required; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("review_gate", **{"population": population})

    def adapt_gate(self, population, *, group_by=None):
        """Adapt a gate to each sample.

        Adapt a gate to every sample by registering the density landmarks of its parent population
        along the gate's axes, learning from the samples the user drew, adjusted or confirmed it on.
        Each sample gets a confidence and a status: keep (the gate already fits), adjust (a
        confident adjustment, which is proposed for the user's review) or review (uncertain, left
        for the user to check by hand, with the reason). Adapt parents before their children: a
        sample under review for a parent stays under review for the children. A gate is moved only
        where it cuts into a population, since populations also move for biological reasons. When
        samples of one donor or subject differ by a stimulation being measured, pass groupBy (the
        metadata field) so that each group keeps one gate. Polygons, rectangles, ellipses, ranges,
        splits and quadrants can be adapted.

        Args:
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Required; a string.
            group_by: Sample metadata field whose samples keep one gate, adapted on their pooled
                events (e.g. donor or subject); default: each sample alone. Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("adapt_gate", **{"population": population, "groupBy": group_by})

    def compare(self, population, group_by, *, channel=None, control=None, pair_by=None, statistic=None):
        """Compare groups of samples.

        Test a population statistic between groups of samples defined by a metadata field (e.g.
        condition), optionally paired by another (e.g. subject): per-group values, effect size with
        confidence interval, and t-test and rank tests.

        Args:
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Required; a string.
            group_by: Metadata field that defines the groups. Required; a string.
            channel: Channel or marker for channel statistics. Optional; a string.
            control: Control sample, for a comparison statistic (overton, sed, pbPositive, pbT,
                ksD). Optional; a string.
            pair_by: Metadata field that pairs samples (optional). Optional; a string.
            statistic: Statistic id (default freqParent). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("compare", **{"population": population, "groupBy": group_by, "channel": channel, "control": control, "pairBy": pair_by, "statistic": statistic})

    def differential_analysis(self, group_by, *, clusters=None, cofactor=None, contrast=None, covariates=None, groups=None, limit=None, markers=None, min_cells=None, min_samples=None, pair_by=None, parent=None, populations=None, test=None):
        """Differential state or abundance across groups.

        Test clusters (a cluster channel from explore) or populations between groups of samples
        defined by a metadata field, with pairing and covariates as fixed effects. test "state"
        (default) is diffcyt-DS-limma: per sample, the median of arcsinh(x / cofactor) of each
        marker in each cluster or population (cofactor 5 for mass cytometry, 150 for fluorescence),
        clusters with at least minCells cells in at least half the samples, a linear model per
        cluster and marker weighted by the cells in each sample, limma's moderated t-statistics with
        a mean-variance trend, and Benjamini-Hochberg adjustment across every cluster and marker
        tested. By default it tests the markers the clustering did not use (state markers). test
        "abundance" tests each cluster's share of the parent population with a quasi-binomial model.
        Rows are sorted by p; logFC is the difference of the medians (contrast minus reference).

        Args:
            group_by: Metadata field that defines the groups. Required; a string.
            clusters: Cluster channel (default: the first one). Optional; a string.
            cofactor: arcsinh cofactor (default 5 for mass cytometry, 150 otherwise). Optional; a
                number.
            contrast: The group tested against the reference (default: the second group). Optional;
                a string.
            covariates: Other metadata fields in the model (e.g. batch). Optional; a list of
                strings.
            groups: Groups to compare, the reference first (default: every value, sorted). Optional;
                a list of strings.
            limit: Rows to return, lowest p first (default 40). Optional; a number.
            markers: Markers to test (default: those the clustering did not use). Optional; a list
                of strings.
            min_cells: Cells a cluster needs in a sample (default 3). Optional; a number.
            min_samples: Samples that need minCells (default: half). Optional; a number.
            pair_by: Metadata field that pairs samples (e.g. subject), as a fixed effect. Optional;
                a string.
            parent: Parent population of the clusters (default: all events). Optional; a string.
            populations: Populations to test instead of clusters (state only). Optional; a list of
                strings.
            test: Marker medians (state, default) or cluster frequencies (abundance). Optional; one
                of "state", "abundance".

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("differential_analysis", **{"groupBy": group_by, "clusters": clusters, "cofactor": cofactor, "contrast": contrast, "covariates": covariates, "groups": groups, "limit": limit, "markers": markers, "minCells": min_cells, "minSamples": min_samples, "pairBy": pair_by, "parent": parent, "populations": populations, "test": test})

    def add_formula_channel(self, expression, *, name=None):
        """Add a formula channel.

        Propose a channel computed for every event of every sample from other channels (compensated
        values): channels in square brackets by marker or detector ([CD4], [FITC-A]), numbers, + - *
        / ^, parentheses and the functions log (base 10), ln, exp, sqrt, abs, asinh, min and max.
        For example a ratio [CD4] / [CD8]. The channel can be gated, plotted and used in statistics
        at once; a ratio A*([x] - B)/([y] - C) goes into Gating-ML exports as fratio.

        Args:
            expression: The formula, e.g. [CD4] / [CD8]. Required; a string.
            name: Channel name (default: from the expression). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("add_formula_channel", **{"expression": expression, "name": name})

    def calibrate_beads(self, sample, values, *, apply_to=None, clustering=None, population=None, unit=None):
        """Calibrate fluorescence with beads.

        Fit a standard curve from a multi-level bead sample (as FlowCal does): the levels are found
        together on the clustering channels, each level's median matched to its value from the
        beads' datasheet (MEF/ERF, dimmest first, null for a level without one), levels near the
        ends of the range left out, and m*ln(x) + b = ln(MEF + MEF_beads) fitted. With applyTo,
        proposes "<channel> <unit>" channels for those samples (acquired with the beads' settings).

        Args:
            sample: The bead sample. Required; a string.
            values: { channel or marker: [value of each level, dimmest first] }. Required; a named
                list (Python: a dict).
            apply_to: Samples to add the calibrated channels to. Optional; a list of strings.
            clustering: Channels to find the levels on (default: the calibrated ones). Optional; a
                list of strings.
            population: The single beads' population (default: found on scatter). Optional; a
                string.
            unit: Unit for every channel (e.g. MEFL), or { channel: unit }. Optional; any value.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("calibrate_beads", **{"sample": sample, "values": values, "applyTo": apply_to, "clustering": clustering, "population": population, "unit": unit})

    def compare_distributions(self, control, *, channel=None, channels=None, control_population=None, population=None, samples=None):
        """Compare samples' distributions with a control.

        Compare a population's distribution on a channel in each sample with a control sample's (an
        FMO, isotype or unstained sample, or a baseline): % positive by SED (Bagwell's enhanced
        normalized subtraction) and by Overton's cumulative subtraction (the K-S Dmax, which
        underestimates it), probability binning (Roederer's T(χ), above 4 for p < 0.01, Baggerly's
        pbStat, and the % of events in excess of the control), and the Kolmogorov-Smirnov D and p.
        With several channels, multivariate probability binning only.

        Args:
            control: Control sample. Required; a string.
            channel: Channel or marker. Optional; a string.
            channels: Several channels, for multivariate probability binning. Optional; a list of
                strings.
            control_population: The control's population (default: the same population). Optional; a
                string.
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Optional; a string.
            samples: Samples to compare (default: every sample but the control). Optional; a list of
                strings.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("compare_distributions", **{"control": control, "channel": channel, "channels": channels, "controlPopulation": control_population, "population": population, "samples": samples})

    def rare_events(self, population, *, blanks=None, cv=None, low=None, low_group_by=None, method=None, samples=None, statistic=None):
        """Rare-event statistics and detection limits.

        For a rare population in each sample: its count with an exact Poisson 95% interval, its
        frequency of the parent with an exact binomial interval, the counting CV, and the parent
        events needed for a target CV. Given blank samples (none of the population expected) and
        optionally low-level samples, also the limit of blank, limit of detection and lower limit of
        quantification (CLSI EP17; Armbruster & Pry 2008), and whether each sample's value is not
        detected, detected below the limit of quantification, or quantifiable.

        Args:
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Required; a string.
            blanks: Blank samples, for the limit of blank. Optional; a list of strings.
            cv: Target CV in % (default 20), for the events needed and the limit of quantification.
                Optional; a number.
            low: Low-level samples, for the limit of detection and of quantification. Optional; a
                list of strings.
            low_group_by: Metadata field grouping low-level samples by level (default: one group).
                Optional; a string.
            method: Limit of blank from mean + 1.645 SD (default) or the 95th percentile. Optional;
                one of "parametric", "nonparametric".
            samples: Samples to report (default: all samples but blanks and low-level ones).
                Optional; a list of strings.
            statistic: What the limits apply to (default freqParent). Optional; one of "freqParent",
                "count".

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("rare_events", **{"population": population, "blanks": blanks, "cv": cv, "low": low, "lowGroupBy": low_group_by, "method": method, "samples": samples, "statistic": statistic})

    def check_robustness(self, population, group_by, *, channel=None, groups=None, pair_by=None, rerun_qc=None, statistic=None):
        """Check a comparison against other analysis choices.

        Repeat a two-group comparison (as compare) under other reasonable analysis choices — each
        gate on the population's path moved 1% and 2% of the axis, the gates adapted to each sample
        or without per-sample adjustments, without acquisition QC (and, with rerunQC, QC re-run with
        MAD 4 and 8), other compensation matrices, a rank test — alone and in random combinations
        (64 analyses), and report whether the conclusion holds (in at least 90% of them), mostly
        holds (70%) or is fragile, which single choices change it, and which change the size of a
        difference found beyond its confidence interval. The declared analysis stays the result;
        report fragility rather than choosing the analysis that gives the answer you want. Takes
        seconds to a minute.

        Args:
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Required; a string.
            group_by: Metadata field that defines the groups. Required; a string.
            channel: Channel or marker for channel statistics. Optional; a string.
            groups: The two groups to compare, reference first (default: the field's two values).
                Optional; a list of strings.
            pair_by: Metadata field that pairs samples (optional). Optional; a string.
            rerun_qc: Also re-run acquisition QC with stricter and looser settings (slower).
                Optional; TRUE or FALSE (Python: True or False).
            statistic: Statistic id (default freqParent). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("check_robustness", **{"population": population, "groupBy": group_by, "channel": channel, "groups": groups, "pairBy": pair_by, "rerunQC": rerun_qc, "statistic": statistic})

    def propose_compensation(self, *, method=None, population=None, samples=None, unstained=None):
        """Propose a compensation matrix from the controls.

        Compute a spillover matrix from the workspace's single-stain controls (samples with the role
        single-stain and a stained channel), optionally within a population of each control (e.g.
        its singlets) and with an unstained sample as the negative reference, and propose it for the
        samples. The user reviews it with your other changes; the result lists the largest spillover
        values and any warnings about the controls.

        Args:
            method: Optional; one of "median", "regression".
            population: Population of each control to use (default: all events). Optional; a string.
            samples: Samples to apply it to (default: every sample that is not a control). Optional;
                a list of strings.
            unstained: Unstained sample used as the negative reference (default: the dim events of
                each control). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("propose_compensation", **{"method": method, "population": population, "samples": samples, "unstained": unstained})

    def annotate_samples(self, samples):
        """Annotate samples.

        Set samples' metadata fields (condition, subject, donor, batch, timepoint, … or any field;
        null removes one), their role (sample, unstained, single-stain, fmo, isotype, bead,
        reference) and, for single-stain controls, the stained channel. Compare, check_robustness,
        adapt_gate (groupBy), propose_compensation and unmix use these. The annotations wait for the
        user's review: until the user accepts, the tools see the current ones.

        Args:
            samples: One entry per sample: {sample, meta: {field: value}, role, stain}. Required; a
                list of strings.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("annotate_samples", **{"samples": samples})

    def run_qc(self, *, add_gate=None, include_controls=None, mad=None, samples=None, variant=None):
        """Run acquisition QC.

        Acquisition QC of samples, as the QC view runs it: PeacoQC (refined by default, or classic
        as in R), a flow-rate check, margin events and per-channel drift. Returns each sample's
        score (0–100), the share of events removed and the findings, worst first. The result is
        proposed: its "QC pass" channel (1 = passed) can be gated at once. With addGate, a "QC pass"
        gate is proposed at the top of the gating tree, which moves every population beneath it when
        the user accepts. Samples the user has already checked keep the user's result. Takes seconds
        per sample.

        Args:
            add_gate: Propose a "QC pass" gate at the top of the tree. Optional; TRUE or FALSE
                (Python: True or False).
            include_controls: Also check controls (default false). Optional; TRUE or FALSE (Python:
                True or False).
            mad: PeacoQC MAD threshold (default 6; lower is stricter). Optional; a number.
            samples: Samples (default: every sample that is not a control). Optional; a list of
                strings.
            variant: Optional; one of "refined", "classic".

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("run_qc", **{"addGate": add_gate, "includeControls": include_controls, "mad": mad, "samples": samples, "variant": variant})

    def unmix(self, *, autofluorescence=None, autofluorescence_mode=None, method=None, recompute=None, samples=None, unstained_population=None):
        """Unmix spectral data.

        Spectral unmixing of raw spectral files (Aurora, ID7000, FACSDiscover and others) with
        reference spectra from the single-stain controls (role single-stain), each gated
        automatically, and autofluorescence signatures from the unstained control (role unstained).
        The user's reference library is used when there is one; otherwise one is computed and
        proposed. Methods: ols (default), wls, wls-fixed, nnls; autofluorescenceMode: none, single,
        perEvent. Returns the unmixed channels (proposed, usable at once), each reference's peak
        detector, stain index and warnings, the panel's complexity index and each sample's median
        residual.

        Args:
            autofluorescence: Extract autofluorescence signatures when building a library (default
                true). Optional; TRUE or FALSE (Python: True or False).
            autofluorescence_mode: none, single or perEvent. Optional; a string.
            method: ols, wls, wls-fixed or nnls. Optional; a string.
            recompute: Recompute your own proposed library. Optional; TRUE or FALSE (Python: True or
                False).
            samples: Samples to unmix (default: every sample that is not a control). Optional; a
                list of strings.
            unstained_population: Population of the unstained control for the signatures (e.g. its
                live single cells). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("unmix", **{"autofluorescence": autofluorescence, "autofluorescenceMode": autofluorescence_mode, "method": method, "recompute": recompute, "samples": samples, "unstainedPopulation": unstained_population})

    def diagnose_unmixing(self, *, population=None, sample=None):
        """Diagnose a spectral unmixing.

        Names the likely causes of a poor spectral unmixing of a sample, most likely first, each
        with its evidence and a fix that was tried on the sample's events (its effect is reported):
        a dye in the sample without a reference (named from the spectral library when it holds it),
        a reference that does not match the dye in the sample (a wrong or mislabeled control; a bead
        control for a stain on cells), a tandem degraded in the sample or in its control (its
        donor's population rises with it), a cell control whose positives carry autofluorescence,
        and autofluorescence the unstained control does not represent (fixation, cells it lacks).
        Uses the reference library and its autofluorescence signatures (unmix first). The user
        applies a fix in the Spectral view's Diagnose tab.

        Args:
            population: Population to diagnose, e.g. its live single cells (default: all events).
                Optional; a string.
            sample: A stained sample (default: the selected one, else the first sample). Optional; a
                string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("diagnose_unmixing", **{"population": population, "sample": sample})

    def explore(self, *, clustering=None, embedding=None, events_per_sample=None, group=None, k=None, markers=None, min_dist=None, n_neighbors=None, neighbors=None, perplexity=None, population=None, populations=None, resolution=None, samples=None, seed=None):
        """Cluster and map cells.

        Cluster the events of a population across samples (flowsom, phenograph (Leiden), louvain,
        kmeans or none; every event gets a cluster) and map them (umap, tsne, pca or none, on an
        equal subsample per sample), as the Explore view does. Returns each cluster's name from
        marker enrichment, frequency and abundance per sample, and the map's faithfulness
        (trustworthiness, continuity, neighbor preservation, sample mixing) with warnings. The
        channels (e.g. "FlowSOM cluster", "UMAP 1") are proposed and usable at once; with
        populations: true the clusters are proposed as populations (category gates) to compare.
        Markers default to the lineage and phenotype markers (viability, DNA and dump channels left
        out).

        Args:
            clustering: flowsom (default), phenograph, louvain, kmeans or none. Optional; a string.
            embedding: umap (default), tsne, pca or none. Optional; a string.
            events_per_sample: Events per sample in the map, default 5000. Optional; a number.
            group: A group of samples instead. Optional; a string.
            k: Metaclusters (FlowSOM) or clusters (k-means), default 12. Optional; a number.
            markers: Channels or markers to cluster on. Optional; a list of strings.
            min_dist: UMAP min_dist, default 0.1. Optional; a number.
            n_neighbors: UMAP n_neighbors, default 15. Optional; a number.
            neighbors: k of the neighbor graph (Leiden, Louvain), default 30. Optional; a number.
            perplexity: t-SNE perplexity, default 30. Optional; a number.
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Optional; a string.
            populations: Propose the clusters as populations. Optional; TRUE or FALSE (Python: True
                or False).
            resolution: Leiden or Louvain resolution, default 1. Optional; a number.
            samples: Samples (default: every sample that is not a control). Optional; a list of
                strings.
            seed: Random seed, default 42. Optional; a number.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("explore", **{"clustering": clustering, "embedding": embedding, "eventsPerSample": events_per_sample, "group": group, "k": k, "markers": markers, "minDist": min_dist, "nNeighbors": n_neighbors, "neighbors": neighbors, "perplexity": perplexity, "population": population, "populations": populations, "resolution": resolution, "samples": samples, "seed": seed})

    def build_figure(self, population, *, group=None, kind=None, name=None, plots=None, sample=None, samples=None):
        """Build a figure.

        Lay out a publication figure, proposed for the user's review: kind gating-strategy shows one
        plot per gate on the path to a population in one sample, each gate on its parent, with
        arrows; kind across-samples shows the same plots (plots: [{x, y, type}], default the
        population's plots in the Gate view) of a population in a row per sample. The plots stay
        live (they follow gate and compensation changes) until export_figure writes the figure.

        Args:
            population: Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events"
                or omitted for all events. Required; a string.
            group: A group of samples instead. Optional; a string.
            kind: Optional; one of "gating-strategy", "across-samples".
            name: Figure name. Optional; a string.
            plots: Plots of an across-samples figure: {x, y (omit for a histogram), type}. Optional;
                a list of strings.
            sample: Sample of a gating strategy (default: the current sample). Optional; a string.
            samples: Samples of an across-samples figure (default: every sample, at most 24).
                Optional; a list of strings.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("build_figure", **{"population": population, "group": group, "kind": kind, "name": name, "plots": plots, "sample": sample, "samples": samples})

    def export_flowjo(self, path, *, counts=None, deidentify=None, files=None, overwrite=None, samples=None):
        """Export a FlowJo workspace.

        Write the workspace as a FlowJo 10 workspace (.wsp), opened by FlowJo 10 and 11: one gating
        tree per sample with its adjustments, the compensation, scales, groups and, by default,
        CytoWeave's counts to check against. With files: true, a .zip holding the workspace and its
        FCS files; with deidentify, identifying keywords are removed from both. Returns the
        populations not written exactly (traced on another scale, or not exported) and why. The file
        must not exist unless overwrite is true.

        Args:
            path: Absolute path of the file to write (.wsp, or .zip with files). Required; a string.
            counts: Include population counts (default true). Optional; TRUE or FALSE (Python: True
                or False).
            deidentify: Optional; TRUE or FALSE (Python: True or False).
            files: Include the FCS files (a .zip). Optional; TRUE or FALSE (Python: True or False).
            overwrite: Optional; TRUE or FALSE (Python: True or False).
            samples: Samples (default: all). Optional; a list of strings.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("export_flowjo", **{"path": path, "counts": counts, "deidentify": deidentify, "files": files, "overwrite": overwrite, "samples": samples})

    def export_fcs(self, path, *, keep_dates=None, overwrite=None, samples=None):
        """Export de-identified FCS files.

        Write de-identified copies of the samples' FCS files: only the keywords needed to read and
        analyze them are kept (operator, specimen and patient fields, free-text comments, dates
        unless keepDates, serial numbers and vendor keywords are removed), the events copied byte
        for byte. A .zip of the files, or an .acs archive with the workspace. Files are named after
        their samples, whose names are kept.

        Args:
            path: Absolute path of the file to write (.zip or .acs). Required; a string.
            keep_dates: Optional; TRUE or FALSE (Python: True or False).
            overwrite: Optional; TRUE or FALSE (Python: True or False).
            samples: Samples (default: all). Optional; a list of strings.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("export_fcs", **{"path": path, "keepDates": keep_dates, "overwrite": overwrite, "samples": samples})

    def export_figure(self, path, *, figure=None, overwrite=None, provenance=None):
        """Export a figure.

        Write a figure (by name; default the newest) as SVG (vector), PNG (3×) or PDF (vector text
        and lines, event rasters as images), chosen by the path's extension. export_report repeats a
        figure for each sample or subject. By default the file carries the analysis behind each plot
        (gates, scales, compensation, file checksums), so opening it in CytoWeave shows what changed
        since.

        Args:
            path: Absolute path of the file to write (.svg, .png or .pdf). Required; a string.
            figure: Figure name. Optional; a string.
            overwrite: Optional; TRUE or FALSE (Python: True or False).
            provenance: Embed the analysis (default true). Optional; TRUE or FALSE (Python: True or
                False).

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("export_figure", **{"path": path, "figure": figure, "overwrite": overwrite, "provenance": provenance})

    def export_events(self, path, *, channels=None, cofactor=None, events_per_sample=None, fraction=None, group=None, overwrite=None, population=None, samples=None, seed=None, values=None, x=None):
        """Export events.

        Write a population's events in several samples, optionally downsampled with a seed (the same
        seed picks the same events; each sample drawn on its own). .fcs: one FCS file of the samples
        concatenated, with the channels they all have (raw values with the spillover matrix when the
        samples share one, else compensated values; values chooses), a SampleID channel numbering
        the samples (names in the CYTOWEAVE_SAMPLE_n keywords) and SourceEvent, each event's index
        in its own file. .zip: one FCS file per sample (raw values, each with its spillover). .h5ad:
        AnnData for scanpy and R: X the chosen channels (default fluorescence and mass) as arcsinh(x
        / cofactor; default 150, 5 for mass cytometry) or compensated values; obs the sample, its
        annotations, event, population (the deepest gate) and a True/False column per gate,
        clusters, QC pass, scatter and time; var the channels and markers; obsm the maps (X_umap,
        X_tsne); uns where it came from.

        Args:
            path: Absolute path of the file to write (.fcs, .zip or .h5ad). Required; a string.
            channels: For .h5ad: the channels of X, by marker or detector. Optional; a list of
                strings.
            cofactor: For .h5ad: the arcsinh cofactor. Optional; a number.
            events_per_sample: Downsample to at most this many events per sample. Optional; a
                number.
            fraction: Downsample to this share of each sample's events (0–1). Optional; a number.
            group: Instead of samples: a group's samples. Optional; a string.
            overwrite: Optional; TRUE or FALSE (Python: True or False).
            population: Population (default: all events). Optional; a string.
            samples: Samples (default: the samples, not controls). Optional; a list of strings.
            seed: Seed of the downsampling (default 1). Optional; a number.
            values: For .fcs: raw values with the spillover matrix, or compensated values. Optional;
                one of "raw", "compensated".
            x: For .h5ad: what X holds (default arcsinh). Optional; one of "arcsinh", "compensated".

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("export_events", **{"path": path, "channels": channels, "cofactor": cofactor, "eventsPerSample": events_per_sample, "fraction": fraction, "group": group, "overwrite": overwrite, "population": population, "samples": samples, "seed": seed, "values": values, "x": x})

    def export_report(self, path, *, by=None, figure=None, group=None, overwrite=None, provenance=None, sample=None, table=None):
        """Export a batch report.

        Write a figure (build_figure, a template's, or the user's) repeated page after page as a
        multi-page PDF or a PowerPoint deck: by sample (the plots of the figure's main sample are
        redrawn on each sample; plots of other samples, such as a control, stay on every page) or by
        an annotation such as subject (each page one value; each plot redrawn on that value's sample
        matching it on the annotations that tell the figure's samples apart, e.g. the stim tube).
        Text placeholders ({sample}, {subject}, {page}, …) are filled; table lists a Tables table's
        columns for each page's samples (as native tables in PowerPoint). Every number printed is
        recorded with the table column or gate it comes from, and the record goes into the file. The
        result lists the pages and notes (a missing tube, replicates).

        Args:
            path: Absolute path of the file to write (.pdf or .pptx). Required; a string.
            by: sample, or an annotation field such as subject (default: the figure's saved choice,
                else sample). Optional; a string.
            figure: Figure name (default: the latest). Optional; a string.
            group: Only the samples of this group (default: the samples, not controls). Optional; a
                string.
            overwrite: Optional; TRUE or FALSE (Python: True or False).
            provenance: Embed the analysis and the record of every number (default true). Optional;
                TRUE or FALSE (Python: True or False).
            sample: By sample: the sample whose plots follow (default: the one most plots are on).
                Optional; a string.
            table: A Tables table to list on each page for the page's samples, if the figure has no
                statistics item. Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("export_report", **{"path": path, "by": by, "figure": figure, "group": group, "overwrite": overwrite, "provenance": provenance, "sample": sample, "table": table})

    def export_table(self, path, *, bead_population=None, beads_per_tube=None, channel=None, control=None, control_population=None, dilution=None, group=None, group_by=None, overwrite=None, populations=None, sample_volume=None, statistic=None, table=None):
        """Export a statistics table.

        Write statistics to a file. .csv or .tsv: a statistic of populations for every sample (as
        statistics_table), one row per sample with its metadata, one column per population. .xlsx:
        an Excel workbook of the Tables table named by table (or that statistic, or with neither,
        every table), values in full precision, with sheets describing each column, the samples
        (files and SHA-256 checksums) and the gating, and the methods. .pzfx: a GraphPad Prism
        project of the table (or the statistic), and with groupBy (an annotation such as condition)
        a column table per statistic with a column per group, as Prism's t tests and ANOVA take.

        Args:
            path: Absolute path of the file to write (.csv, .tsv, .xlsx or .pzfx). Required; a
                string.
            bead_population: For absoluteCount: the counting beads' population. Optional; a string.
            beads_per_tube: For absoluteCount: beads in the tube. Optional; a number.
            channel: Channel or marker for channel statistics. Optional; a string.
            control: Control sample for comparison statistics. Optional; a string.
            control_population: The control's population (default: the same population). Optional; a
                string.
            dilution: For concentration and absoluteCount: a dilution factor, or the sample
                annotation that holds it. Optional; a string.
            group: Group name (default: all samples). Optional; a string.
            group_by: For .pzfx: the annotation whose values become Prism's columns. Optional; a
                string.
            overwrite: Optional; TRUE or FALSE (Python: True or False).
            populations: Populations (default: all). Optional; a list of strings.
            sample_volume: For absoluteCount: µL of sample in the tube. Optional; a number.
            statistic: Statistic id (default freqParent). Optional; a string.
            table: A table in Tables (for .xlsx and .pzfx; its columns as Tables shows them).
                Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("export_table", **{"path": path, "beadPopulation": bead_population, "beadsPerTube": beads_per_tube, "channel": channel, "control": control, "controlPopulation": control_population, "dilution": dilution, "group": group, "groupBy": group_by, "overwrite": overwrite, "populations": populations, "sampleVolume": sample_volume, "statistic": statistic, "table": table})

    def list_templates(self):
        """List analysis templates.

        The analysis templates in the library (saved by the user or save_template): each one's name,
        populations and the markers its channels measure; and the published gating strategies
        (OMIP-101 major leukocyte populations, OMIP-090 regulatory T cells) that apply_template
        places on the data, with their citations and where they differ from the articles.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("list_templates")

    def save_template(self, name, *, population=None):
        """Save the analysis as a template.

        Save the workspace's analysis (or one population and those under it) as a template in the
        library: the gates, scales, plots, tables and figure layouts, with channels described by
        marker (scatter and time by name) so that it applies to another panel. Gates on computed
        channels and per-sample adjustments are left out and listed.

        Args:
            name: Template name. Required; a string.
            population: Keep only this population and those under it (default: the whole tree).
                Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("save_template", **{"name": name, "population": population})

    def apply_template(self, template, *, channels=None, figures=None, parent=None, sample=None):
        """Apply an analysis template.

        Apply a template from the library, or a published gating strategy (omip-101, omip-090; see
        list_templates), to the open samples: each of its channels is matched by marker (preferring
        the same area/height suffix), scatter and time by name, and the report says how each matched
        and which populations could not be applied (with the reason). A strategy's gates are placed
        on the events of one sample (sample, default the current one), each from its parent
        population: density peaks for scatter, valleys between a marker's modes for positive and
        negative cells, and come with suggested Cell Ontology terms. The gates and figures are
        proposed for the user's review; gates keep their position in data values, so check them
        across samples with review_gate and adjust with adapt_gate. channels overrides a match:
        {"CD3": "FL4-A"}.

        Args:
            template: Template name, or a strategy id (omip-101). Required; a string.
            channels: Template marker or channel name → channel here. Optional; a named list
                (Python: a dict).
            figures: Also propose its figures (default true). Optional; TRUE or FALSE (Python: True
                or False).
            parent: Population to put the template's top gates under (default: the top of the tree).
                Optional; a string.
            sample: Sample whose events a strategy's gates are placed on (default: the current
                sample). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("apply_template", **{"template": template, "channels": channels, "figures": figures, "parent": parent, "sample": sample})

    def suggest_cell_types(self, *, populations=None, propose=None, sample=None):
        """Suggest Cell Ontology terms.

        Suggest a Cell Ontology term for each population (or the ones named) from its marker
        phenotype in a sample: which side of each gate's markers it lies on and, for scatter gates,
        where it sits, never from its name. Each suggestion has a confidence (exact: every marker
        the term requires is gated; likely: only negative markers are not gated) and the markers it
        rests on. With propose: true, the top terms are proposed for the user to confirm; confirmed
        terms go into the FlowJo and Gating-ML exports and the methods.

        Args:
            populations: Populations (default: all). Optional; a list of strings.
            propose: Propose the top terms for the user to confirm. Optional; TRUE or FALSE (Python:
                True or False).
            sample: Sample name or id (default: the sample shown in the window). Optional; a string.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("suggest_cell_types", **{"populations": populations, "propose": propose, "sample": sample})

    def titration(self, mode, *, channel=None, linear_max=None, population=None, rsd_en=None, samples=None, save=None):
        """Analyze a titration or voltage walk.

        A reagent titration (samples stained with a series of amounts of one antibody, read from
        their names, such as "125 ng" or "1:200", or an "amount" annotation) or a detector voltage
        walk (samples acquired at a series of PMT voltages, from each file's $PnV). On one channel
        (default: the one the names mention, or found from the data), within a population (default:
        one named like lymphocytes), each step's positive and negative cells give the stain index
        (Maecker), separation index (Bigos) and medians. Titration: a saturation curve fitted to the
        stain index; the recommended amount is the first tested at or above twice the amount giving
        90% of saturation (Bonilla et al. 2024). Voltage walk: the minimum voltage, where the
        negative cells' rSD reaches 2.5 times the detector's electronic noise (rsdEN from the
        cytometer's baseline report, or estimated from the walk), and the maximum, where the
        positive cells' 99th percentile reaches the top of the linear range (linearMax, default 90%
        of the range). With save, the result is proposed for the workspace, and the methods describe
        it.

        Args:
            mode: Required; one of "titration", "voltage".
            channel: Channel or marker (default: detected). Optional; a string.
            linear_max: Top of the detector's linear range (voltage walk). Optional; a number.
            population: Population to analyze within (default: a lymphocyte gate if any, else all
                events). Optional; a string.
            rsd_en: The detector's electronic noise rSD (voltage walk). Optional; a number.
            samples: The samples of the series (default: found from names and voltages). Optional; a
                list of strings.
            save: Propose the result for the workspace. Optional; TRUE or FALSE (Python: True or
                False).

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("titration", **{"mode": mode, "channel": channel, "linearMax": linear_max, "population": population, "rsdEN": rsd_en, "samples": samples, "save": save})

    def watch_folder(self, action, *, beads=None, existing=None, path=None, qc=None):
        """Watch an instrument's export folder.

        QC as files are acquired: action start watches a folder (absolute path) the instrument
        exports to; each FCS file is added to the workspace once complete and checked at once
        (acquisition QC for samples and controls, Q and B for bead files, against the instrument's
        Levey–Jennings rules). The folder is only read. Files already there wait for action
        existing. action status lists every file with its result (call it again to follow new
        files); stop ends the watch.

        Args:
            action: Required; one of "start", "stop", "existing", "status".
            beads: Measure Q and B on bead files (default true). Optional; TRUE or FALSE (Python:
                True or False).
            existing: Also check the files already there (start). Optional; TRUE or FALSE (Python:
                True or False).
            path: Folder to watch (start). Optional; a string.
            qc: Run acquisition QC on samples (default true). Optional; TRUE or FALSE (Python: True
                or False).

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("watch_folder", **{"action": action, "beads": beads, "existing": existing, "path": path, "qc": qc})

    def proposals(self):
        """Proposals and the user's decisions.

        Your open proposal (what is waiting for the user's review) and the user's recent decisions
        on proposals (accepted or rejected, by whom).

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("proposals")

    def methods(self):
        """Write the methods.

        A methods paragraph for the analysis in the workspace, with numbered references and DOIs.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("methods")

    def export_gating_ml(self):
        """Export gates as Gating-ML.

        The gating strategy as ISAC Gating-ML 2.0 XML text.

        Returns:
            A Result: the message and the data CytoWeave answered with.
        """
        return self.call("export_gating_ml")
