# Generated by clients/generate.mjs from clients/tools.json; do not edit by hand.

#' Describe the workspace
#'
#' The open workspace: its samples (name, events, role, metadata, channels with markers),
#' groups, the gating tree with counts for the current sample, compensation matrices, derived
#' results, and what the window shows. Start here.
#'
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_workspace_summary <- function(cw = cw_default()) {
  cw_call("workspace_summary", cw = cw)
}

#' Open FCS files
#'
#' Open FCS files, folders of FCS files (each folder becomes a group), CytoWeave workspaces
#' (.cwz), FlowJo workspaces (.wsp) and FlowJo 11 workbenches (.flowjo), FACSDiva experiments
#' exported as XML (these open in the import dialog for the user, with a fidelity report and a
#' count comparison), SpectroFlo experiments (.Expt, whose reference controls the user can mark
#' for spectral unmixing), Gating-ML files, or CSV files of events (a row per event, a column
#' per channel; each becomes a sample, with the columns' kinds and scales guessed and checked,
#' reported in data.csv), by absolute path on this computer. A CSV whose first column names
#' samples annotates them instead.
#'
#' @param paths Absolute paths of files or folders. Required; a list of strings.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_open_files <- function(paths, cw = cw_default()) {
  cw_call("open_files", paths = .cw_array(paths), cw = cw)
}

#' Open an example experiment
#'
#' Generate and open a simulated example experiment as a new workspace: pbmc-immunophenotyping,
#' flowjo-workspace (four samples and a FlowJo workspace, which opens in the FlowJo import
#' dialog for the user), spectral-25color, cell-cycle, proliferation, calcium-flux (Indo-1
#' ratio over time, for kinetics), plate-screen (a 96-well drug screen, one file per well, for
#' plates and dose-response), bead-immunoassay (a LEGENDplex-like cytokine bead assay with
#' standards, for bead_assay), cytof-cohort, cytof-barcoded (a pooled, palladium-barcoded
#' plate), index-sort, qc-showcase or bead-qc (30 daily runs of multi-level beads for Q, B and
#' Levey–Jennings).
#'
#' @param id Required; one of "pbmc-immunophenotyping", "flowjo-workspace", "spectral-25color",
#' "cell-cycle", "proliferation", "calcium-flux", "plate-screen", "bead-immunoassay",
#' "cytof-cohort", "cytof-barcoded", "index-sort", "qc-showcase", "bead-qc".
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_open_example <- function(id, cw = cw_default()) {
  cw_call("open_example", id = id, cw = cw)
}

#' Show a sample, population or view
#'
#' Change what the window shows: a sample, a population, and/or a view (gate, qc, compensate,
#' spectral, explore, tables, plates, compare, figures, report).
#'
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Optional; a string.
#' @param sample Sample name or id (default: the sample shown in the window). Optional; a
#' string.
#' @param view View to show. Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_select <- function(population = NULL, sample = NULL, view = NULL, cw = cw_default()) {
  cw_call("select", population = population, sample = sample, view = view, cw = cw)
}

#' List populations with counts
#'
#' The gating tree for a sample: every population's path, gate type and channels, event count,
#' \% of parent and \% of total.
#'
#' @param sample Sample name or id (default: the sample shown in the window). Optional; a
#' string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_list_populations <- function(sample = NULL, cw = cw_default()) {
  cw_call("list_populations", sample = sample, cw = cw)
}

#' Statistics of a population
#'
#' Count, frequencies and per-channel statistics (median, mean, geometric mean, SD, robust SD,
#' CV, robust CV, percentiles) of one population in one sample, on compensated values.
#'
#' @param channels Channels or markers (default: all fluorescence channels). Optional; a list
#' of strings.
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Optional; a string.
#' @param sample Sample name or id (default: the sample shown in the window). Optional; a
#' string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_population_statistics <- function(channels = NULL, population = NULL, sample = NULL, cw = cw_default()) {
  cw_call("population_statistics", channels = .cw_array(channels), population = population, sample = sample, cw = cw)
}

#' A statistic across samples
#'
#' One or more statistics of one or more populations for every sample (or a group): e.g.
#' freqParent of CD4 T cells, or median of CD25 in Tregs. Statistics: count, freqParent,
#' freqTotal, freqGrandparent, median, mean, geomean, sd, rsd, cv, rcv, percentile, mode,
#' positive; for rare events countLow and countHigh (exact Poisson 95\% limits), countCV,
#' freqLow and freqHigh (exact binomial 95\% limits of freqParent); concentration (/µL from
#' $VOL) and absoluteCount (/µL from counting beads); and, against a control sample's
#' population on the channel, overton and sed (\% positive), pbPositive and pbT (probability
#' binning) and ksD.
#'
#' @param bead_population For absoluteCount: the counting beads' population. Optional; a
#' string.
#' @param beads_per_tube For absoluteCount: beads in the tube. Optional; a number.
#' @param channel Channel or marker for channel statistics. Optional; a string.
#' @param control Control sample for overton, sed, pbPositive, pbT and ksD (e.g. an FMO).
#' Optional; a string.
#' @param control_population The control's population (default: the same population). Optional;
#' a string.
#' @param dilution For concentration and absoluteCount: a dilution factor, or the sample
#' annotation that holds it. Optional; a string.
#' @param group Group name (default: all samples). Optional; a string.
#' @param populations Populations (default: all). Optional; a list of strings.
#' @param sample_volume For absoluteCount: µL of sample in the tube. Optional; a number.
#' @param statistic Statistic id (default freqParent). Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_statistics_table <- function(bead_population = NULL, beads_per_tube = NULL, channel = NULL, control = NULL, control_population = NULL, dilution = NULL, group = NULL, populations = NULL, sample_volume = NULL, statistic = NULL, cw = cw_default()) {
  cw_call("statistics_table", beadPopulation = bead_population, beadsPerTube = beads_per_tube, channel = channel, control = control, controlPopulation = control_population, dilution = dilution, group = group, populations = .cw_array(populations), sampleVolume = sample_volume, statistic = statistic, cw = cw)
}

#' Render a plot
#'
#' A PNG image of a plot: a population of a sample on one or two channels, with the child gates
#' drawn and labeled. Types: pseudocolor, dot, density, contour, zebra, histogram.
#'
#' @param x X channel or marker. Required; a string.
#' @param height Height in pixels (default 480). Optional; a number.
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Optional; a string.
#' @param sample Sample name or id (default: the sample shown in the window). Optional; a
#' string.
#' @param type Plot type. Optional; a string.
#' @param width Width in pixels (default 520). Optional; a number.
#' @param y Y channel or marker (omit for a histogram). Optional; a string.
#' @param file Optional; save the plot to this path as a PNG file.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_render_plot <- function(x, height = NULL, population = NULL, sample = NULL, type = NULL, width = NULL, y = NULL, file = NULL, cw = cw_default()) {
  result <- cw_call("render_plot", x = x, height = height, population = population, sample = sample, type = type, width = width, y = y, cw = cw)
  if (!is.null(file)) cw_save_image(result, file)
  result
}

#' Create a gate
#'
#' Add a gate under a parent population. Coordinates are data values (as on the plot axes).
#' Types and coordinates: rectangle {xMin, xMax, yMin, yMax} (omit a bound to leave it open),
#' polygon {vertices: [[x, y], ...]}, ellipse {center: [x, y], semiAxes in fractions of the
#' axes [rx, ry], angle in degrees}, range on one channel {min, max}, quadrant {at: [x, y]}
#' (creates four populations), split on one channel {threshold} (two populations). The gate is
#' proposed for the user's review (shown as proposed, usable as a parent at once). Returns the
#' new populations with their counts.
#'
#' @param type Required; one of "rectangle", "polygon", "ellipse", "range", "quadrant",
#' "split".
#' @param x X channel or marker. Required; a string.
#' @param coordinates Type-specific coordinates in data values. Required; a named list (Python:
#' a dict).
#' @param name Name (default: from the markers). Optional; a string.
#' @param parent Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events" or
#' omitted for all events. Optional; a string.
#' @param sample Sample whose counts are reported (default: the current sample); the gate
#' applies to every sample. Optional; a string.
#' @param y Y channel or marker (not for range or split). Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_create_gate <- function(type, x, coordinates, name = NULL, parent = NULL, sample = NULL, y = NULL, cw = cw_default()) {
  cw_call("create_gate", type = type, x = x, coordinates = coordinates, name = name, parent = parent, sample = sample, y = y, cw = cw)
}

#' Propose a gate from the data
#'
#' Add a gate found from the data's density: method "density" gates the population around a
#' point (at: [x, y] in data values) like a magic wand; "singlets" gates single cells on an
#' area-versus-height plot (x = FSC-A, y = FSC-H); "valley" splits one channel at the density
#' minimum between its two main modes. The explanation says what was found. The gate is
#' proposed for the user's review.
#'
#' @param method Required; one of "density", "singlets", "valley".
#' @param x X channel or marker. Required; a string.
#' @param at [x, y] data values (density). Optional; a list of strings.
#' @param name Name. Optional; a string.
#' @param parent Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All events" or
#' omitted for all events. Optional; a string.
#' @param sample Sample name or id (default: the sample shown in the window). Optional; a
#' string.
#' @param y Y channel or marker. Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_auto_gate <- function(method, x, at = NULL, name = NULL, parent = NULL, sample = NULL, y = NULL, cw = cw_default()) {
  cw_call("auto_gate", method = method, x = x, at = .cw_array(at), name = name, parent = parent, sample = sample, y = y, cw = cw)
}

#' Rename, recolor or delete a gate
#'
#' Rename a population, change its color, or delete it (with its subpopulations). Changes to
#' gates the user has accepted wait for the user's review; changes to gates you proposed apply
#' at once.
#'
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Required; a string.
#' @param color New color (#rrggbb). Optional; a string.
#' @param delete Optional; TRUE or FALSE (Python: True or False).
#' @param name New name. Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_edit_gate <- function(population, color = NULL, delete = NULL, name = NULL, cw = cw_default()) {
  cw_call("edit_gate", population = population, color = color, delete = delete, name = name, cw = cw)
}

#' Review a gate across samples
#'
#' A gate's frequency on every sample with a robust z-score against the cohort and the boundary
#' robustness (how much the frequency depends on exactly where the boundary is), outliers
#' first.
#'
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Required; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_review_gate <- function(population, cw = cw_default()) {
  cw_call("review_gate", population = population, cw = cw)
}

#' Adapt a gate to each sample
#'
#' Adapt a gate to every sample by registering the density landmarks of its parent population
#' along the gate's axes, learning from the samples the user drew, adjusted or confirmed it on.
#' Each sample gets a confidence and a status: keep (the gate already fits), adjust (a
#' confident adjustment, which is proposed for the user's review) or review (uncertain, left
#' for the user to check by hand, with the reason). Adapt parents before their children: a
#' sample under review for a parent stays under review for the children. A gate is moved only
#' where it cuts into a population, since populations also move for biological reasons. When
#' samples of one donor or subject differ by a stimulation being measured, pass groupBy (the
#' metadata field) so that each group keeps one gate. Polygons, rectangles, ellipses, ranges,
#' splits and quadrants can be adapted.
#'
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Required; a string.
#' @param group_by Sample metadata field whose samples keep one gate, adapted on their pooled
#' events (e.g. donor or subject); default: each sample alone. Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_adapt_gate <- function(population, group_by = NULL, cw = cw_default()) {
  cw_call("adapt_gate", population = population, groupBy = group_by, cw = cw)
}

#' Compare groups of samples
#'
#' Test a population statistic between groups of samples defined by a metadata field (e.g.
#' condition), optionally paired by another (e.g. subject): per-group values, effect size with
#' confidence interval, and t-test and rank tests.
#'
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Required; a string.
#' @param group_by Metadata field that defines the groups. Required; a string.
#' @param channel Channel or marker for channel statistics. Optional; a string.
#' @param control Control sample, for a comparison statistic (overton, sed, pbPositive, pbT,
#' ksD). Optional; a string.
#' @param pair_by Metadata field that pairs samples (optional). Optional; a string.
#' @param statistic Statistic id (default freqParent). Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_compare <- function(population, group_by, channel = NULL, control = NULL, pair_by = NULL, statistic = NULL, cw = cw_default()) {
  cw_call("compare", population = population, groupBy = group_by, channel = channel, control = control, pairBy = pair_by, statistic = statistic, cw = cw)
}

#' Differential state or abundance across groups
#'
#' Test clusters (a cluster channel from explore) or populations between groups of samples
#' defined by a metadata field, with pairing and covariates as fixed effects. test "state"
#' (default) is diffcyt-DS-limma: per sample, the median of arcsinh(x / cofactor) of each
#' marker in each cluster or population (cofactor 5 for mass cytometry, 150 for fluorescence),
#' clusters with at least minCells cells in at least half the samples, a linear model per
#' cluster and marker weighted by the cells in each sample, limma's moderated t-statistics with
#' a mean-variance trend, and Benjamini-Hochberg adjustment across every cluster and marker
#' tested. By default it tests the markers the clustering did not use (state markers). test
#' "abundance" tests each cluster's share of the parent population with a quasi-binomial model.
#' Rows are sorted by p; logFC is the difference of the medians (contrast minus reference).
#'
#' @param group_by Metadata field that defines the groups. Required; a string.
#' @param clusters Cluster channel (default: the first one). Optional; a string.
#' @param cofactor arcsinh cofactor (default 5 for mass cytometry, 150 otherwise). Optional; a
#' number.
#' @param contrast The group tested against the reference (default: the second group).
#' Optional; a string.
#' @param covariates Other metadata fields in the model (e.g. batch). Optional; a list of
#' strings.
#' @param groups Groups to compare, the reference first (default: every value, sorted).
#' Optional; a list of strings.
#' @param limit Rows to return, lowest p first (default 40). Optional; a number.
#' @param markers Markers to test (default: those the clustering did not use). Optional; a list
#' of strings.
#' @param min_cells Cells a cluster needs in a sample (default 3). Optional; a number.
#' @param min_samples Samples that need minCells (default: half). Optional; a number.
#' @param pair_by Metadata field that pairs samples (e.g. subject), as a fixed effect.
#' Optional; a string.
#' @param parent Parent population of the clusters (default: all events). Optional; a string.
#' @param populations Populations to test instead of clusters (state only). Optional; a list of
#' strings.
#' @param test Marker medians (state, default) or cluster frequencies (abundance). Optional;
#' one of "state", "abundance".
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_differential_analysis <- function(group_by, clusters = NULL, cofactor = NULL, contrast = NULL, covariates = NULL, groups = NULL, limit = NULL, markers = NULL, min_cells = NULL, min_samples = NULL, pair_by = NULL, parent = NULL, populations = NULL, test = NULL, cw = cw_default()) {
  cw_call("differential_analysis", groupBy = group_by, clusters = clusters, cofactor = cofactor, contrast = contrast, covariates = .cw_array(covariates), groups = .cw_array(groups), limit = limit, markers = .cw_array(markers), minCells = min_cells, minSamples = min_samples, pairBy = pair_by, parent = parent, populations = .cw_array(populations), test = test, cw = cw)
}

#' Add a formula channel
#'
#' Propose a channel computed for every event of every sample from other channels (compensated
#' values): channels in square brackets by marker or detector ([CD4], [FITC-A]), numbers, + - *
#' / ^, parentheses and the functions log (base 10), ln, exp, sqrt, abs, asinh, min and max.
#' For example a ratio [CD4] / [CD8]. The channel can be gated, plotted and used in statistics
#' at once; a ratio A*([x] - B)/([y] - C) goes into Gating-ML exports as fratio.
#'
#' @param expression The formula, e.g. [CD4] / [CD8]. Required; a string.
#' @param name Channel name (default: from the expression). Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_add_formula_channel <- function(expression, name = NULL, cw = cw_default()) {
  cw_call("add_formula_channel", expression = expression, name = name, cw = cw)
}

#' Calibrate fluorescence with beads
#'
#' Fit a standard curve from a multi-level bead sample (as FlowCal does): the levels are found
#' together on the clustering channels, each level's median matched to its value from the
#' beads' datasheet (MEF/ERF, dimmest first, null for a level without one), levels near the
#' ends of the range left out, and m*ln(x) + b = ln(MEF + MEF_beads) fitted. With applyTo,
#' proposes "<channel> <unit>" channels for those samples (acquired with the beads' settings).
#'
#' @param sample The bead sample. Required; a string.
#' @param values { channel or marker: [value of each level, dimmest first] }. Required; a named
#' list (Python: a dict).
#' @param apply_to Samples to add the calibrated channels to. Optional; a list of strings.
#' @param clustering Channels to find the levels on (default: the calibrated ones). Optional; a
#' list of strings.
#' @param population The single beads' population (default: found on scatter). Optional; a
#' string.
#' @param unit Unit for every channel (e.g. MEFL), or { channel: unit }. Optional; any value.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_calibrate_beads <- function(sample, values, apply_to = NULL, clustering = NULL, population = NULL, unit = NULL, cw = cw_default()) {
  cw_call("calibrate_beads", sample = sample, values = values, applyTo = .cw_array(apply_to), clustering = .cw_array(clustering), population = population, unit = unit, cw = cw)
}

#' Compare samples' distributions with a control
#'
#' Compare a population's distribution on a channel in each sample with a control sample's (an
#' FMO, isotype or unstained sample, or a baseline): \% positive by SED (Bagwell's enhanced
#' normalized subtraction) and by Overton's cumulative subtraction (the K-S Dmax, which
#' underestimates it), probability binning (Roederer's T(χ), above 4 for p < 0.01, Baggerly's
#' pbStat, and the \% of events in excess of the control), and the Kolmogorov-Smirnov D and p.
#' With several channels, multivariate probability binning only.
#'
#' @param control Control sample. Required; a string.
#' @param channel Channel or marker. Optional; a string.
#' @param channels Several channels, for multivariate probability binning. Optional; a list of
#' strings.
#' @param control_population The control's population (default: the same population). Optional;
#' a string.
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Optional; a string.
#' @param samples Samples to compare (default: every sample but the control). Optional; a list
#' of strings.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_compare_distributions <- function(control, channel = NULL, channels = NULL, control_population = NULL, population = NULL, samples = NULL, cw = cw_default()) {
  cw_call("compare_distributions", control = control, channel = channel, channels = .cw_array(channels), controlPopulation = control_population, population = population, samples = .cw_array(samples), cw = cw)
}

#' Rare-event statistics and detection limits
#'
#' For a rare population in each sample: its count with an exact Poisson 95\% interval, its
#' frequency of the parent with an exact binomial interval, the counting CV, and the parent
#' events needed for a target CV. Given blank samples (none of the population expected) and
#' optionally low-level samples, also the limit of blank, limit of detection and lower limit of
#' quantification (CLSI EP17; Armbruster & Pry 2008), and whether each sample's value is not
#' detected, detected below the limit of quantification, or quantifiable.
#'
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Required; a string.
#' @param blanks Blank samples, for the limit of blank. Optional; a list of strings.
#' @param cv Target CV in \% (default 20), for the events needed and the limit of
#' quantification. Optional; a number.
#' @param low Low-level samples, for the limit of detection and of quantification. Optional; a
#' list of strings.
#' @param low_group_by Metadata field grouping low-level samples by level (default: one group).
#' Optional; a string.
#' @param method Limit of blank from mean + 1.645 SD (default) or the 95th percentile.
#' Optional; one of "parametric", "nonparametric".
#' @param samples Samples to report (default: all samples but blanks and low-level ones).
#' Optional; a list of strings.
#' @param statistic What the limits apply to (default freqParent). Optional; one of
#' "freqParent", "count".
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_rare_events <- function(population, blanks = NULL, cv = NULL, low = NULL, low_group_by = NULL, method = NULL, samples = NULL, statistic = NULL, cw = cw_default()) {
  cw_call("rare_events", population = population, blanks = .cw_array(blanks), cv = cv, low = .cw_array(low), lowGroupBy = low_group_by, method = method, samples = .cw_array(samples), statistic = statistic, cw = cw)
}

#' Check a comparison against other analysis choices
#'
#' Repeat a two-group comparison (as compare) under other reasonable analysis choices — each
#' gate on the population's path moved 1\% and 2\% of the axis, the gates adapted to each
#' sample or without per-sample adjustments, without acquisition QC (and, with rerunQC, QC
#' re-run with MAD 4 and 8), other compensation matrices, a rank test — alone and in random
#' combinations (64 analyses), and report whether the conclusion holds (in at least 90\% of
#' them), mostly holds (70\%) or is fragile, which single choices change it, and which change
#' the size of a difference found beyond its confidence interval. The declared analysis stays
#' the result; report fragility rather than choosing the analysis that gives the answer you
#' want. Takes seconds to a minute.
#'
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Required; a string.
#' @param group_by Metadata field that defines the groups. Required; a string.
#' @param channel Channel or marker for channel statistics. Optional; a string.
#' @param groups The two groups to compare, reference first (default: the field's two values).
#' Optional; a list of strings.
#' @param pair_by Metadata field that pairs samples (optional). Optional; a string.
#' @param rerun_qc Also re-run acquisition QC with stricter and looser settings (slower).
#' Optional; TRUE or FALSE (Python: True or False).
#' @param statistic Statistic id (default freqParent). Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_check_robustness <- function(population, group_by, channel = NULL, groups = NULL, pair_by = NULL, rerun_qc = NULL, statistic = NULL, cw = cw_default()) {
  cw_call("check_robustness", population = population, groupBy = group_by, channel = channel, groups = .cw_array(groups), pairBy = pair_by, rerunQC = rerun_qc, statistic = statistic, cw = cw)
}

#' Propose a compensation matrix from the controls
#'
#' Compute a spillover matrix from the workspace's single-stain controls (samples with the role
#' single-stain and a stained channel), optionally within a population of each control (e.g.
#' its singlets) and with an unstained sample as the negative reference, and propose it for the
#' samples. The user reviews it with your other changes; the result lists the largest spillover
#' values and any warnings about the controls.
#'
#' @param method Optional; one of "median", "regression".
#' @param population Population of each control to use (default: all events). Optional; a
#' string.
#' @param samples Samples to apply it to (default: every sample that is not a control).
#' Optional; a list of strings.
#' @param unstained Unstained sample used as the negative reference (default: the dim events of
#' each control). Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_propose_compensation <- function(method = NULL, population = NULL, samples = NULL, unstained = NULL, cw = cw_default()) {
  cw_call("propose_compensation", method = method, population = population, samples = .cw_array(samples), unstained = unstained, cw = cw)
}

#' Annotate samples
#'
#' Set samples' metadata fields (condition, subject, donor, batch, timepoint, … or any field;
#' null removes one), their role (sample, unstained, single-stain, fmo, isotype, bead,
#' reference) and, for single-stain controls, the stained channel. Compare, check_robustness,
#' adapt_gate (groupBy), propose_compensation and unmix use these. The annotations wait for the
#' user's review: until the user accepts, the tools see the current ones.
#'
#' @param samples One entry per sample: {sample, meta: {field: value}, role, stain}. Required;
#' a list of strings.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_annotate_samples <- function(samples, cw = cw_default()) {
  cw_call("annotate_samples", samples = .cw_array(samples), cw = cw)
}

#' Run acquisition QC
#'
#' Acquisition QC of samples, as the QC view runs it: PeacoQC (refined by default, or classic
#' as in R), a flow-rate check, margin events and per-channel drift. Returns each sample's
#' score (0–100), the share of events removed and the findings, worst first. The result is
#' proposed: its "QC pass" channel (1 = passed) can be gated at once. With addGate, a "QC pass"
#' gate is proposed at the top of the gating tree, which moves every population beneath it when
#' the user accepts. Samples the user has already checked keep the user's result. Takes seconds
#' per sample.
#'
#' @param add_gate Propose a "QC pass" gate at the top of the tree. Optional; TRUE or FALSE
#' (Python: True or False).
#' @param include_controls Also check controls (default false). Optional; TRUE or FALSE
#' (Python: True or False).
#' @param mad PeacoQC MAD threshold (default 6; lower is stricter). Optional; a number.
#' @param samples Samples (default: every sample that is not a control). Optional; a list of
#' strings.
#' @param variant Optional; one of "refined", "classic".
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_run_qc <- function(add_gate = NULL, include_controls = NULL, mad = NULL, samples = NULL, variant = NULL, cw = cw_default()) {
  cw_call("run_qc", addGate = add_gate, includeControls = include_controls, mad = mad, samples = .cw_array(samples), variant = variant, cw = cw)
}

#' Unmix spectral data
#'
#' Spectral unmixing of raw spectral files (Aurora, ID7000, FACSDiscover and others) with
#' reference spectra from the single-stain controls (role single-stain), each gated
#' automatically, and autofluorescence signatures from the unstained control (role unstained).
#' The user's reference library is used when there is one; otherwise one is computed and
#' proposed. Methods: ols (default), wls, wls-fixed, nnls; autofluorescenceMode: none, single,
#' perEvent. Returns the unmixed channels (proposed, usable at once), each reference's peak
#' detector, stain index and warnings, the panel's complexity index and each sample's median
#' residual.
#'
#' @param autofluorescence Extract autofluorescence signatures when building a library (default
#' true). Optional; TRUE or FALSE (Python: True or False).
#' @param autofluorescence_mode none, single or perEvent. Optional; a string.
#' @param method ols, wls, wls-fixed or nnls. Optional; a string.
#' @param recompute Recompute your own proposed library. Optional; TRUE or FALSE (Python: True
#' or False).
#' @param samples Samples to unmix (default: every sample that is not a control). Optional; a
#' list of strings.
#' @param unstained_population Population of the unstained control for the signatures (e.g. its
#' live single cells). Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_unmix <- function(autofluorescence = NULL, autofluorescence_mode = NULL, method = NULL, recompute = NULL, samples = NULL, unstained_population = NULL, cw = cw_default()) {
  cw_call("unmix", autofluorescence = autofluorescence, autofluorescenceMode = autofluorescence_mode, method = method, recompute = recompute, samples = .cw_array(samples), unstainedPopulation = unstained_population, cw = cw)
}

#' Kinetics: a signal over time
#'
#' A population's signal against acquisition time, as in a calcium flux: the ratio of two
#' channels (Indo-1 violet/blue: numerator and denominator) or one channel (Fluo-4), its median
#' (or mean) per time bin, smoothed, and the response measured against the baseline before the
#' stimulus: baseline, peak, time to peak, half-max time, amplitude, fold, area under the
#' curve, end level and the percentage of responding events (above the baseline's 99th
#' percentile, net of the baseline's share). The stimulus is where acquisition paused (the tube
#' taken out to add it) unless given; without a pause the response's onset is used. Without
#' channels, an Indo-1 pair is looked for by name. Returns one row per sample.
#'
#' @param bin_width Time bin width in seconds (default automatic). Optional; a number.
#' @param channel A single channel instead of a ratio. Optional; a string.
#' @param denominator Ratio denominator channel (e.g. Indo-1 blue). Optional; a string.
#' @param numerator Ratio numerator channel (e.g. Indo-1 violet). Optional; a string.
#' @param population Population (e.g. Lymphocytes/Live/T cells; default all events). Optional;
#' a string.
#' @param response_end End of the response window in seconds. Optional; a number.
#' @param samples Samples (default: every sample that is not a control). Optional; a list of
#' strings.
#' @param smoothing Moving-average window in bins (default 3). Optional; any value.
#' @param statistic median (default) or mean. Optional; a string.
#' @param stimulus Stimulus time in seconds (default: the pause in acquisition). Optional; a
#' number.
#' @param threshold Threshold for responding events (default the baseline's 99th percentile).
#' Optional; a number.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_kinetics <- function(bin_width = NULL, channel = NULL, denominator = NULL, numerator = NULL, population = NULL, response_end = NULL, samples = NULL, smoothing = NULL, statistic = NULL, stimulus = NULL, threshold = NULL, cw = cw_default()) {
  cw_call("kinetics", binWidth = bin_width, channel = channel, denominator = denominator, numerator = numerator, population = population, responseEnd = response_end, samples = .cw_array(samples), smoothing = smoothing, statistic = statistic, stimulus = stimulus, threshold = threshold, cw = cw)
}

#' Plates and heat maps
#'
#' The plates of the workspace (samples acquired from wells, placed by their $WELLID or WELL ID
#' keywords, names such as Plate1_A01.fcs, or "well" annotations): each plate's format and
#' wells, and the layout's annotation fields with their values. With statistic (and population,
#' channel), a heat map: the statistic of every well as a grid (rows A…, columns 1…), and Z′
#' (Zhang et al. 1999) from the positive and negative control wells named by controlField
#' (default the "control" annotation; values positive/pos/+ and negative/neg/−). Wells with
#' fewer than minEvents events in the population (for a percentage, in the population it is a
#' percentage of) are listed.
#'
#' @param channel Channel or marker, for channel statistics. Optional; a string.
#' @param control_field Annotation naming the control wells. Optional; a string.
#' @param min_events Flag wells with fewer events (default 100). Optional; a number.
#' @param plate Plate name (default the first). Optional; a string.
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Optional; a string.
#' @param robust Robust Z′ (median and MAD). Optional; TRUE or FALSE (Python: True or False).
#' @param statistic Statistic id: freqParent (default), count, median, mean, geomean, cv, ….
#' Optional; a string.
#' @param value Percentile or threshold, for percentile and positive. Optional; a number.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_plate <- function(channel = NULL, control_field = NULL, min_events = NULL, plate = NULL, population = NULL, robust = NULL, statistic = NULL, value = NULL, cw = cw_default()) {
  cw_call("plate", channel = channel, controlField = control_field, minEvents = min_events, plate = plate, population = population, robust = robust, statistic = statistic, value = value, cw = cw)
}

#' Propose a plate layout
#'
#' Annotate a plate's wells from a layout, proposed for the user's review (as
#' annotate_samples): CSV text with a "well" column (A01 or A1), an optional "plate" column and
#' one column per field (compound, dose such as "10 nM", control, standard, specimen, dilution,
#' …), or plate maps as R's plater writes them (a block per field: the field's name and 1, 2,
#' …, then a row per plate row A, B, …). Wells without a sample are reported.
#'
#' @param layout The layout as CSV text. Required; a string.
#' @param plate Plate to annotate when the layout has no plate column (default the first).
#' Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_plate_layout <- function(layout, plate = NULL, cw = cw_default()) {
  cw_call("plate_layout", layout = layout, plate = plate, cw = cw)
}

#' Dose-response curves
#'
#' Dose-response curves of a plate: a statistic of every well against its dose (doseField, an
#' annotation such as "10 nM"; units converted to the most common), one curve per groupField
#' value (default the compound annotation), fitted by least squares to a four- (LL.4) or
#' five-parameter (LL.5) log-logistic model in R drc's parameterization. Returns for each group
#' the EC50 (IC50 for a falling curve) with its 95\% CI (delta method, log scale), Hill slope
#' (negative for a falling curve), bottom, top, R², and flags: no-effect (no better than a flat
#' line, F test p ≥ 0.05), extrapolated (EC50 outside the doses), wide-ci (CI wider than
#' 100-fold), at-bound. normalize: none, controls (\% of controls: negative 0\%, positive
#' 100\%) or inhibition (100 − that), with the asymptotes fixed at 0 and 100 unless
#' fixBottom/fixTop is false. Control wells (controlField) are left out of the curves; the
#' plate's Z′ is returned.
#'
#' @param channel Channel or marker, for channel statistics. Optional; a string.
#' @param control_field Annotation naming positive and negative control wells. Optional; a
#' string.
#' @param dose_field Annotation holding each well's dose. Optional; a string.
#' @param fix_bottom With normalize: fix the bottom at 0 (default true). Optional; TRUE or
#' FALSE (Python: True or False).
#' @param fix_top With normalize: fix the top at 100 (default true). Optional; TRUE or FALSE
#' (Python: True or False).
#' @param group_field Annotation giving one curve per value (e.g. compound). Optional; a
#' string.
#' @param model LL.4 (default) or LL.5. Optional; a string.
#' @param normalize none (default), controls or inhibition. Optional; a string.
#' @param plate Plate name (default the first). Optional; a string.
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Optional; a string.
#' @param statistic Statistic id (default freqParent). Optional; a string.
#' @param value Percentile or threshold, for percentile and positive. Optional; a number.
#' @param weighting none (default), 1/y or 1/y2. Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_dose_response <- function(channel = NULL, control_field = NULL, dose_field = NULL, fix_bottom = NULL, fix_top = NULL, group_field = NULL, model = NULL, normalize = NULL, plate = NULL, population = NULL, statistic = NULL, value = NULL, weighting = NULL, cw = cw_default()) {
  cw_call("dose_response", channel = channel, controlField = control_field, doseField = dose_field, fixBottom = fix_bottom, fixTop = fix_top, groupField = group_field, model = model, normalize = normalize, plate = plate, population = population, statistic = statistic, value = value, weighting = weighting, cw = cw)
}

#' Bead immunoassay (LEGENDplex, CBA)
#'
#' A bead-based immunoassay on a plate: in each bead group's population (the bead sizes, gated
#' on scatter) the beads of each analyte are found by their level of the classification dye
#' (found once from all wells), each analyte's reporter MFI (median by default) on the standard
#' wells (standardField: C0 … C7, or concentrations) gives a standard curve (five-parameter
#' log-logistic by default, weighted 1/Y²), and every other well's concentration is read from
#' it and multiplied by its dilution (dilutionField). Standard concentrations: top (the top
#' standard, or tops per analyte) divided by factor (default 4) per step; C0 or 0 is a blank.
#' Returns per analyte its quantifiable range (standards back-calculating within 20\% with CV ≤
#' 20\%, 25\% at the ends; FDA 2018), limit of detection (blanks' mean + 3 SD), curve and
#' standards' recovery, and per sample (replicates by sampleField averaged) the concentrations
#' with flags (< LLOQ, > ULOQ, < LOD, below curve).
#'
#' @param groups Bead groups: [{population, analytes: [names from the dimmest bead to the
#' brightest]}]. Required; a list of strings.
#' @param classification_channel Classification (bead ID) channel (default an APC-like
#' channel). Optional; a string.
#' @param dilution_field Annotation holding each sample's dilution. Optional; a string.
#' @param factor Dilution between standards (default 4). Optional; a number.
#' @param min_beads Fewer beads of an analyte than this: no value (default 50). Optional; a
#' number.
#' @param model LL.5 (default) or LL.4. Optional; a string.
#' @param plate Plate name (default the first). Optional; a string.
#' @param reporter_channel Reporter channel (default PE). Optional; a string.
#' @param sample_field Annotation whose wells are replicates. Optional; a string.
#' @param standard_field Annotation naming the standards (default standard). Optional; a
#' string.
#' @param standard_mode auto, concentration, levels-top-high (C7 top) or levels-top-low (S1
#' top). Optional; a string.
#' @param statistic median (default), geometric or mean. Optional; a string.
#' @param top Top standard's concentration. Optional; a number.
#' @param tops Top standard per analyte: {name: concentration}. Optional; a named list (Python:
#' a dict).
#' @param unit Concentration unit (default pg/mL). Optional; a string.
#' @param weighting 1/y2 (default), 1/y or none. Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_bead_assay <- function(groups, classification_channel = NULL, dilution_field = NULL, factor = NULL, min_beads = NULL, model = NULL, plate = NULL, reporter_channel = NULL, sample_field = NULL, standard_field = NULL, standard_mode = NULL, statistic = NULL, top = NULL, tops = NULL, unit = NULL, weighting = NULL, cw = cw_default()) {
  cw_call("bead_assay", groups = .cw_array(groups), classificationChannel = classification_channel, dilutionField = dilution_field, factor = factor, minBeads = min_beads, model = model, plate = plate, reporterChannel = reporter_channel, sampleField = sample_field, standardField = standard_field, standardMode = standard_mode, statistic = statistic, top = top, tops = tops, unit = unit, weighting = weighting, cw = cw)
}

#' Diagnose a spectral unmixing
#'
#' Names the likely causes of a poor spectral unmixing of a sample, most likely first, each
#' with its evidence and a fix that was tried on the sample's events (its effect is reported):
#' a dye in the sample without a reference (named from the spectral library when it holds it),
#' a reference that does not match the dye in the sample (a wrong or mislabeled control; a bead
#' control for a stain on cells), a tandem degraded in the sample or in its control (its
#' donor's population rises with it), a cell control whose positives carry autofluorescence,
#' and autofluorescence the unstained control does not represent (fixation, cells it lacks).
#' Uses the reference library and its autofluorescence signatures (unmix first). The user
#' applies a fix in the Spectral view's Diagnose tab.
#'
#' @param population Population to diagnose, e.g. its live single cells (default: all events).
#' Optional; a string.
#' @param sample A stained sample (default: the selected one, else the first sample). Optional;
#' a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_diagnose_unmixing <- function(population = NULL, sample = NULL, cw = cw_default()) {
  cw_call("diagnose_unmixing", population = population, sample = sample, cw = cw)
}

#' Cluster and map cells
#'
#' Cluster the events of a population across samples (flowsom, phenograph (Leiden), louvain,
#' kmeans or none; every event gets a cluster) and map them (umap, tsne, pca or none, on an
#' equal subsample per sample), as the Explore view does. Returns each cluster's name from
#' marker enrichment, frequency and abundance per sample, and the map's faithfulness
#' (trustworthiness, continuity, neighbor preservation, sample mixing) with warnings. The
#' channels (e.g. "FlowSOM cluster", "UMAP 1") are proposed and usable at once; with
#' populations: true the clusters are proposed as populations (category gates) to compare.
#' Markers default to the lineage and phenotype markers (viability, DNA and dump channels left
#' out).
#'
#' @param clustering flowsom (default), phenograph, louvain, kmeans or none. Optional; a
#' string.
#' @param embedding umap (default), tsne, pca or none. Optional; a string.
#' @param events_per_sample Events per sample in the map, default 5000. Optional; a number.
#' @param group A group of samples instead. Optional; a string.
#' @param k Metaclusters (FlowSOM) or clusters (k-means), default 12. Optional; a number.
#' @param markers Channels or markers to cluster on. Optional; a list of strings.
#' @param min_dist UMAP min_dist, default 0.1. Optional; a number.
#' @param n_neighbors UMAP n_neighbors, default 15. Optional; a number.
#' @param neighbors k of the neighbor graph (Leiden, Louvain), default 30. Optional; a number.
#' @param perplexity t-SNE perplexity, default 30. Optional; a number.
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Optional; a string.
#' @param populations Propose the clusters as populations. Optional; TRUE or FALSE (Python:
#' True or False).
#' @param resolution Leiden or Louvain resolution, default 1. Optional; a number.
#' @param samples Samples (default: every sample that is not a control). Optional; a list of
#' strings.
#' @param seed Random seed, default 42. Optional; a number.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_explore <- function(clustering = NULL, embedding = NULL, events_per_sample = NULL, group = NULL, k = NULL, markers = NULL, min_dist = NULL, n_neighbors = NULL, neighbors = NULL, perplexity = NULL, population = NULL, populations = NULL, resolution = NULL, samples = NULL, seed = NULL, cw = cw_default()) {
  cw_call("explore", clustering = clustering, embedding = embedding, eventsPerSample = events_per_sample, group = group, k = k, markers = .cw_array(markers), minDist = min_dist, nNeighbors = n_neighbors, neighbors = neighbors, perplexity = perplexity, population = population, populations = populations, resolution = resolution, samples = .cw_array(samples), seed = seed, cw = cw)
}

#' Build a figure
#'
#' Lay out a publication figure, proposed for the user's review: kind gating-strategy shows one
#' plot per gate on the path to a population in one sample, each gate on its parent, with
#' arrows; kind across-samples shows the same plots (plots: [{x, y, type}], default the
#' population's plots in the Gate view) of a population in a row per sample. The plots stay
#' live (they follow gate and compensation changes) until export_figure writes the figure.
#'
#' @param population Population name, path ("Lymphocytes/Single cells/CD3+") or id; "All
#' events" or omitted for all events. Required; a string.
#' @param group A group of samples instead. Optional; a string.
#' @param kind Optional; one of "gating-strategy", "across-samples".
#' @param name Figure name. Optional; a string.
#' @param plots Plots of an across-samples figure: {x, y (omit for a histogram), type}.
#' Optional; a list of strings.
#' @param sample Sample of a gating strategy (default: the current sample). Optional; a string.
#' @param samples Samples of an across-samples figure (default: every sample, at most 24).
#' Optional; a list of strings.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_build_figure <- function(population, group = NULL, kind = NULL, name = NULL, plots = NULL, sample = NULL, samples = NULL, cw = cw_default()) {
  cw_call("build_figure", population = population, group = group, kind = kind, name = name, plots = .cw_array(plots), sample = sample, samples = .cw_array(samples), cw = cw)
}

#' Export a FlowJo workspace
#'
#' Write the workspace as a FlowJo 10 workspace (.wsp), opened by FlowJo 10 and 11: one gating
#' tree per sample with its adjustments, the compensation, scales, groups and, by default,
#' CytoWeave's counts to check against. With files: true, a .zip holding the workspace and its
#' FCS files; with deidentify, identifying keywords are removed from both. Returns the
#' populations not written exactly (traced on another scale, or not exported) and why. The file
#' must not exist unless overwrite is true.
#'
#' @param path Absolute path of the file to write (.wsp, or .zip with files). Required; a
#' string.
#' @param counts Include population counts (default true). Optional; TRUE or FALSE (Python:
#' True or False).
#' @param deidentify Optional; TRUE or FALSE (Python: True or False).
#' @param files Include the FCS files (a .zip). Optional; TRUE or FALSE (Python: True or
#' False).
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param samples Samples (default: all). Optional; a list of strings.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_flowjo <- function(path, counts = NULL, deidentify = NULL, files = NULL, overwrite = NULL, samples = NULL, cw = cw_default()) {
  cw_call("export_flowjo", path = path, counts = counts, deidentify = deidentify, files = files, overwrite = overwrite, samples = .cw_array(samples), cw = cw)
}

#' Export de-identified FCS files
#'
#' Write de-identified copies of the samples' FCS files: only the keywords needed to read and
#' analyze them are kept (operator, specimen and patient fields, free-text comments, dates
#' unless keepDates, serial numbers and vendor keywords are removed), the events copied byte
#' for byte. A .zip of the files, or an .acs archive with the workspace. Files are named after
#' their samples, whose names are kept.
#'
#' @param path Absolute path of the file to write (.zip or .acs). Required; a string.
#' @param keep_dates Optional; TRUE or FALSE (Python: True or False).
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param samples Samples (default: all). Optional; a list of strings.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_fcs <- function(path, keep_dates = NULL, overwrite = NULL, samples = NULL, cw = cw_default()) {
  cw_call("export_fcs", path = path, keepDates = keep_dates, overwrite = overwrite, samples = .cw_array(samples), cw = cw)
}

#' Export a figure
#'
#' Write a figure (by name; default the newest) as SVG (vector), PNG (3×) or PDF (vector text
#' and lines, event rasters as images), chosen by the path's extension. export_report repeats a
#' figure for each sample or subject. By default the file carries the analysis behind each plot
#' (gates, scales, compensation, file checksums), so opening it in CytoWeave shows what changed
#' since.
#'
#' @param path Absolute path of the file to write (.svg, .png or .pdf). Required; a string.
#' @param figure Figure name. Optional; a string.
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param provenance Embed the analysis (default true). Optional; TRUE or FALSE (Python: True
#' or False).
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_figure <- function(path, figure = NULL, overwrite = NULL, provenance = NULL, cw = cw_default()) {
  cw_call("export_figure", path = path, figure = figure, overwrite = overwrite, provenance = provenance, cw = cw)
}

#' Export events
#'
#' Write a population's events in several samples, optionally downsampled with a seed (the same
#' seed picks the same events; each sample drawn on its own). .fcs: one FCS file of the samples
#' concatenated, with the channels they all have (raw values with the spillover matrix when the
#' samples share one, else compensated values; values chooses), a SampleID channel numbering
#' the samples (names in the CYTOWEAVE_SAMPLE_n keywords) and SourceEvent, each event's index
#' in its own file. .zip: one FCS file per sample (raw values, each with its spillover). .h5ad:
#' AnnData for scanpy and R: X the chosen channels (default fluorescence and mass) as arcsinh(x
#' / cofactor; default 150, 5 for mass cytometry) or compensated values; obs the sample, its
#' annotations, event, population (the deepest gate) and a True/False column per gate,
#' clusters, QC pass, scatter and time; var the channels and markers; obsm the maps (X_umap,
#' X_tsne); uns where it came from.
#'
#' @param path Absolute path of the file to write (.fcs, .zip or .h5ad). Required; a string.
#' @param channels For .h5ad: the channels of X, by marker or detector. Optional; a list of
#' strings.
#' @param cofactor For .h5ad: the arcsinh cofactor. Optional; a number.
#' @param events_per_sample Downsample to at most this many events per sample. Optional; a
#' number.
#' @param fraction Downsample to this share of each sample's events (0–1). Optional; a number.
#' @param group Instead of samples: a group's samples. Optional; a string.
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param population Population (default: all events). Optional; a string.
#' @param samples Samples (default: the samples, not controls). Optional; a list of strings.
#' @param seed Seed of the downsampling (default 1). Optional; a number.
#' @param values For .fcs: raw values with the spillover matrix, or compensated values.
#' Optional; one of "raw", "compensated".
#' @param x For .h5ad: what X holds (default arcsinh). Optional; one of "arcsinh",
#' "compensated".
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_events <- function(path, channels = NULL, cofactor = NULL, events_per_sample = NULL, fraction = NULL, group = NULL, overwrite = NULL, population = NULL, samples = NULL, seed = NULL, values = NULL, x = NULL, cw = cw_default()) {
  cw_call("export_events", path = path, channels = .cw_array(channels), cofactor = cofactor, eventsPerSample = events_per_sample, fraction = fraction, group = group, overwrite = overwrite, population = population, samples = .cw_array(samples), seed = seed, values = values, x = x, cw = cw)
}

#' Export a batch report
#'
#' Write a figure (build_figure, a template's, or the user's) repeated page after page as a
#' multi-page PDF or a PowerPoint deck: by sample (the plots of the figure's main sample are
#' redrawn on each sample; plots of other samples, such as a control, stay on every page) or by
#' an annotation such as subject (each page one value; each plot redrawn on that value's sample
#' matching it on the annotations that tell the figure's samples apart, e.g. the stim tube).
#' Text placeholders ({sample}, {subject}, {page}, …) are filled; table lists a Tables table's
#' columns for each page's samples (as native tables in PowerPoint). Every number printed is
#' recorded with the table column or gate it comes from, and the record goes into the file. The
#' result lists the pages and notes (a missing tube, replicates).
#'
#' @param path Absolute path of the file to write (.pdf or .pptx). Required; a string.
#' @param by sample, or an annotation field such as subject (default: the figure's saved
#' choice, else sample). Optional; a string.
#' @param figure Figure name (default: the latest). Optional; a string.
#' @param group Only the samples of this group (default: the samples, not controls). Optional;
#' a string.
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param provenance Embed the analysis and the record of every number (default true).
#' Optional; TRUE or FALSE (Python: True or False).
#' @param sample By sample: the sample whose plots follow (default: the one most plots are on).
#' Optional; a string.
#' @param table A Tables table to list on each page for the page's samples, if the figure has
#' no statistics item. Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_report <- function(path, by = NULL, figure = NULL, group = NULL, overwrite = NULL, provenance = NULL, sample = NULL, table = NULL, cw = cw_default()) {
  cw_call("export_report", path = path, by = by, figure = figure, group = group, overwrite = overwrite, provenance = provenance, sample = sample, table = table, cw = cw)
}

#' Export a statistics table
#'
#' Write statistics to a file. .csv or .tsv: a statistic of populations for every sample (as
#' statistics_table), one row per sample with its metadata, one column per population. .xlsx:
#' an Excel workbook of the Tables table named by table (or that statistic, or with neither,
#' every table), values in full precision, with sheets describing each column, the samples
#' (files and SHA-256 checksums) and the gating, and the methods. .pzfx: a GraphPad Prism
#' project of the table (or the statistic), and with groupBy (an annotation such as condition)
#' a column table per statistic with a column per group, as Prism's t tests and ANOVA take.
#'
#' @param path Absolute path of the file to write (.csv, .tsv, .xlsx or .pzfx). Required; a
#' string.
#' @param bead_population For absoluteCount: the counting beads' population. Optional; a
#' string.
#' @param beads_per_tube For absoluteCount: beads in the tube. Optional; a number.
#' @param channel Channel or marker for channel statistics. Optional; a string.
#' @param control Control sample for comparison statistics. Optional; a string.
#' @param control_population The control's population (default: the same population). Optional;
#' a string.
#' @param dilution For concentration and absoluteCount: a dilution factor, or the sample
#' annotation that holds it. Optional; a string.
#' @param group Group name (default: all samples). Optional; a string.
#' @param group_by For .pzfx: the annotation whose values become Prism's columns. Optional; a
#' string.
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param populations Populations (default: all). Optional; a list of strings.
#' @param sample_volume For absoluteCount: µL of sample in the tube. Optional; a number.
#' @param statistic Statistic id (default freqParent). Optional; a string.
#' @param table A table in Tables (for .xlsx and .pzfx; its columns as Tables shows them).
#' Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_table <- function(path, bead_population = NULL, beads_per_tube = NULL, channel = NULL, control = NULL, control_population = NULL, dilution = NULL, group = NULL, group_by = NULL, overwrite = NULL, populations = NULL, sample_volume = NULL, statistic = NULL, table = NULL, cw = cw_default()) {
  cw_call("export_table", path = path, beadPopulation = bead_population, beadsPerTube = beads_per_tube, channel = channel, control = control, controlPopulation = control_population, dilution = dilution, group = group, groupBy = group_by, overwrite = overwrite, populations = .cw_array(populations), sampleVolume = sample_volume, statistic = statistic, table = table, cw = cw)
}

#' List analysis templates
#'
#' The analysis templates in the library (saved by the user or save_template): each one's name,
#' populations and the markers its channels measure; and the published gating strategies
#' (OMIP-101 major leukocyte populations, OMIP-090 regulatory T cells) that apply_template
#' places on the data, with their citations and where they differ from the articles.
#'
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_list_templates <- function(cw = cw_default()) {
  cw_call("list_templates", cw = cw)
}

#' Save the analysis as a template
#'
#' Save the workspace's analysis (or one population and those under it) as a template in the
#' library: the gates, scales, plots, tables and figure layouts, with channels described by
#' marker (scatter and time by name) so that it applies to another panel. Gates on computed
#' channels and per-sample adjustments are left out and listed.
#'
#' @param name Template name. Required; a string.
#' @param population Keep only this population and those under it (default: the whole tree).
#' Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_save_template <- function(name, population = NULL, cw = cw_default()) {
  cw_call("save_template", name = name, population = population, cw = cw)
}

#' Apply an analysis template
#'
#' Apply a template from the library (or a template file's contents, templateJSON), or a
#' published gating strategy (omip-101, omip-090; see list_templates), to the open samples:
#' each of its channels is matched by marker (preferring the same area/height suffix), scatter
#' and time by name, and the report says how each matched and which populations could not be
#' applied (with the reason). A strategy's gates are placed on the events of one sample
#' (sample, default the current one), each from its parent population: density peaks for
#' scatter, valleys between a marker's modes for positive and negative cells, and come with
#' suggested Cell Ontology terms. The gates and figures are proposed for the user's review;
#' gates keep their position in data values, so check them across samples with review_gate and
#' adjust with adapt_gate. channels overrides a match: {"CD3": "FL4-A"}.
#'
#' @param channels Template marker or channel name → channel here. Optional; a named list
#' (Python: a dict).
#' @param figures Also propose its figures (default true). Optional; TRUE or FALSE (Python:
#' True or False).
#' @param parent Population to put the template's top gates under (default: the top of the
#' tree). Optional; a string.
#' @param sample Sample whose events a strategy's gates are placed on (default: the current
#' sample). Optional; a string.
#' @param template Template name, or a strategy id (omip-101). Optional; a string.
#' @param template_json Instead of template: the contents of a template file (.cwt). Optional;
#' a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_apply_template <- function(channels = NULL, figures = NULL, parent = NULL, sample = NULL, template = NULL, template_json = NULL, cw = cw_default()) {
  cw_call("apply_template", channels = channels, figures = figures, parent = parent, sample = sample, template = template, templateJSON = template_json, cw = cw)
}

#' Suggest Cell Ontology terms
#'
#' Suggest a Cell Ontology term for each population (or the ones named) from its marker
#' phenotype in a sample: which side of each gate's markers it lies on and, for scatter gates,
#' where it sits, never from its name. Each suggestion has a confidence (exact: every marker
#' the term requires is gated; likely: only negative markers are not gated) and the markers it
#' rests on. With propose: true, the top terms are proposed for the user to confirm; confirmed
#' terms go into the FlowJo and Gating-ML exports and the methods.
#'
#' @param populations Populations (default: all). Optional; a list of strings.
#' @param propose Propose the top terms for the user to confirm. Optional; TRUE or FALSE
#' (Python: True or False).
#' @param sample Sample name or id (default: the sample shown in the window). Optional; a
#' string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_suggest_cell_types <- function(populations = NULL, propose = NULL, sample = NULL, cw = cw_default()) {
  cw_call("suggest_cell_types", populations = .cw_array(populations), propose = propose, sample = sample, cw = cw)
}

#' Analyze a titration or voltage walk
#'
#' A reagent titration (samples stained with a series of amounts of one antibody, read from
#' their names, such as "125 ng" or "1:200", or an "amount" annotation) or a detector voltage
#' walk (samples acquired at a series of PMT voltages, from each file's $PnV). On one channel
#' (default: the one the names mention, or found from the data), within a population (default:
#' one named like lymphocytes), each step's positive and negative cells give the stain index
#' (Maecker), separation index (Bigos) and medians. Titration: a saturation curve fitted to the
#' stain index; the recommended amount is the first tested at or above twice the amount giving
#' 90\% of saturation (Bonilla et al. 2024). Voltage walk: the minimum voltage, where the
#' negative cells' rSD reaches 2.5 times the detector's electronic noise (rsdEN from the
#' cytometer's baseline report, or estimated from the walk), and the maximum, where the
#' positive cells' 99th percentile reaches the top of the linear range (linearMax, default 90\%
#' of the range). With save, the result is proposed for the workspace, and the methods describe
#' it.
#'
#' @param mode Required; one of "titration", "voltage".
#' @param channel Channel or marker (default: detected). Optional; a string.
#' @param linear_max Top of the detector's linear range (voltage walk). Optional; a number.
#' @param population Population to analyze within (default: a lymphocyte gate if any, else all
#' events). Optional; a string.
#' @param rsd_en The detector's electronic noise rSD (voltage walk). Optional; a number.
#' @param samples The samples of the series (default: found from names and voltages). Optional;
#' a list of strings.
#' @param save Propose the result for the workspace. Optional; TRUE or FALSE (Python: True or
#' False).
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_titration <- function(mode, channel = NULL, linear_max = NULL, population = NULL, rsd_en = NULL, samples = NULL, save = NULL, cw = cw_default()) {
  cw_call("titration", mode = mode, channel = channel, linearMax = linear_max, population = population, rsdEN = rsd_en, samples = .cw_array(samples), save = save, cw = cw)
}

#' Watch an instrument's export folder
#'
#' QC as files are acquired: action start watches a folder (absolute path) the instrument
#' exports to; each FCS file is added to the workspace once complete and checked at once
#' (acquisition QC for samples and controls, Q and B for bead files, against the instrument's
#' Levey–Jennings rules). The folder is only read. Files already there wait for action
#' existing. action status lists every file with its result (call it again to follow new
#' files); stop ends the watch.
#'
#' @param action Required; one of "start", "stop", "existing", "status".
#' @param beads Measure Q and B on bead files (default true). Optional; TRUE or FALSE (Python:
#' True or False).
#' @param existing Also check the files already there (start). Optional; TRUE or FALSE (Python:
#' True or False).
#' @param path Folder to watch (start). Optional; a string.
#' @param qc Run acquisition QC on samples (default true). Optional; TRUE or FALSE (Python:
#' True or False).
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_watch_folder <- function(action, beads = NULL, existing = NULL, path = NULL, qc = NULL, cw = cw_default()) {
  cw_call("watch_folder", action = action, beads = beads, existing = existing, path = path, qc = qc, cw = cw)
}

#' Proposals and the user's decisions
#'
#' Your open proposal (what is waiting for the user's review) and the user's recent decisions
#' on proposals (accepted or rejected, by whom).
#'
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_proposals <- function(cw = cw_default()) {
  cw_call("proposals", cw = cw)
}

#' Write the methods
#'
#' A methods paragraph for the analysis in the workspace, with numbered references and DOIs.
#'
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_methods <- function(cw = cw_default()) {
  cw_call("methods", cw = cw)
}

#' Export the workspace
#'
#' Write the workspace as a CytoWeave workspace file (.cwz): the samples (by file name and
#' checksum, not their events), annotations, gates, compensation, scales, tables, figures and
#' results, which CytoWeave opens again with the FCS files beside it. Open proposals are saved
#' as proposals. The file must not exist unless overwrite is true.
#'
#' @param path Absolute path of the file to write (.cwz). Required; a string.
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_workspace <- function(path, overwrite = NULL, cw = cw_default()) {
  cw_call("export_workspace", path = path, overwrite = overwrite, cw = cw)
}

#' Predict a virtual FMO
#'
#' Where a population's negative for a channel's dye would end without that dye: a virtual FMO
#' control, predicted from the panel's spread model (fitted to the single-stain or reference
#' controls when the compensation or the spectral spreading matrix was computed) and the
#' unstained control's autofluorescence. Each event's value without the dye is drawn from its
#' own brightness of every other dye; the threshold is the given percentile (quantile, default
#' 0.995). Returns the threshold in the channel's data units, the unstained control's alone,
#' the real FMO control's when the workspace has one (role fmo), the dyes the spread comes
#' from, and with versus (another channel) the threshold binned along it, as an FMO shows on a
#' plot. It is a guide, not a replacement for a real FMO on dim or critical markers. addGate
#' proposes a range gate from the threshold up (named name).
#'
#' @param sample Sample name. Required; a string.
#' @param channel The channel (or its marker) whose dye is left out. Required; a string.
#' @param add_gate Propose a range gate from the threshold up. Optional; TRUE or FALSE (Python:
#' True or False).
#' @param name Name of the proposed gate. Optional; a string.
#' @param population Population (path or name; default all events). Optional; a string.
#' @param quantile Percentile of the predicted negative (default 0.995). Optional; a number.
#' @param versus Optional: another channel to bin the threshold along. Optional; a string.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_virtual_fmo <- function(sample, channel, add_gate = NULL, name = NULL, population = NULL, quantile = NULL, versus = NULL, cw = cw_default()) {
  cw_call("virtual_fmo", sample = sample, channel = channel, addGate = add_gate, name = name, population = population, quantile = quantile, versus = versus, cw = cw)
}

#' Make a reproducibility certificate
#'
#' Write a reproducibility certificate of the analysis (.acs, an ISAC Archival Cytometry
#' Standard archive): the workspace, the FCS files (unless includeData is false: then only
#' their SHA-256), the channels the analysis stored, the gates as Gating-ML, the methods, and
#' certificate.json, which records the CytoWeave version, every input's SHA-256, the analyses
#' and their seeds, the head of the hash-chained change log, MIFlowCyt and every number
#' reported: each population's count in each sample, every table cell, and every saved
#' comparison of one measure. Every number is computed from the files to make it;
#' verify_certificate computes them again. Returns the fingerprint (SHA-256 of
#' certificate.json) to quote with the analysis, and warnings (a saved comparison that no
#' longer matches the analysis). The file must not exist unless overwrite is true.
#'
#' @param path Absolute path of the file to write (.acs). Required; a string.
#' @param include_data Include the FCS files (default true); without them, verifying needs the
#' files. Optional; TRUE or FALSE (Python: True or False).
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_certificate <- function(path, include_data = NULL, overwrite = NULL, cw = cw_default()) {
  cw_call("export_certificate", path = path, includeData = include_data, overwrite = overwrite, cw = cw)
}

#' Write a review report
#'
#' Write a review report of the analysis: one self-contained HTML file (.html) for a PI,
#' collaborator or reviewer, opened in any browser without CytoWeave: the samples with their
#' SHA-256 checksums, the gating hierarchy and every population's count in every sample, every
#' sample's gates drawn on its own events (plots "all", the default; "none" leaves them out;
#' includeControls draws the controls too), the workspace's figures and tables, the saved
#' comparisons, the methods, MIFlowCyt and the change log. Every number is traced (a click
#' shows its sample, file checksum, gates and the counts behind it); the numbers are those a
#' reproducibility certificate records. The file loads nothing from the network. The file must
#' not exist unless overwrite is true.
#'
#' @param path Absolute path of the file to write (.html). Required; a string.
#' @param include_controls Optional; TRUE or FALSE (Python: True or False).
#' @param overwrite Optional; TRUE or FALSE (Python: True or False).
#' @param plots Optional; one of "all", "none".
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_review_report <- function(path, include_controls = NULL, overwrite = NULL, plots = NULL, cw = cw_default()) {
  cw_call("export_review_report", path = path, includeControls = include_controls, overwrite = overwrite, plots = plots, cw = cw)
}

#' Verify a reproducibility certificate
#'
#' Verify a CytoWeave reproducibility certificate (absolute path of the .acs file): check every
#' file's SHA-256, the workspace, the change log's chain and certificate.json's fingerprint,
#' compute every number again from the files and compare them bit for bit. A certificate
#' written without its data needs data (a folder, or FCS file paths; files are recognized by
#' their checksums). Returns the verdict (confirmed, incomplete or differs), a summary, and the
#' numbers that differ. The analysis in the window is not changed.
#'
#' @param path Absolute path of the certificate (.acs). Required; a string.
#' @param data A folder with the FCS files, or a list of FCS file paths, for a certificate
#' without its data. Optional; any value.
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_verify_certificate <- function(path, data = NULL, cw = cw_default()) {
  cw_call("verify_certificate", path = path, data = data, cw = cw)
}

#' Export gates as Gating-ML
#'
#' The gating strategy as ISAC Gating-ML 2.0 XML text.
#'
#' @param cw A connection from cw_connect() (default: the last one made).
#' @return A cytoweave_result: the message and the data CytoWeave answered with.
#' @export
cw_export_gating_ml <- function(cw = cw_default()) {
  cw_call("export_gating_ml", cw = cw)
}
